<?php 
	/**
	 * Write an cascaded array into a CSV file.
	 * @param type $fileDesc the CSV file descriptor (should be opened).
	 * @param type $array the array to turn to CSV.
	 * @param type $depth (optional) the depth to show in the CSV.
	 */
	function addArrayToCSV( $array, $depth = 0) {
		$depthArr = array();
		$retStr ="";
		for($i=0; $i < $depth; $i++) {
			$depthArr[] ='';
		}
		//Billrun_Factory::log()->log(print_r($array,1),Zend_Log::DEBUG);
		$line = $depthArr;
		foreach ($array as $key => $value) {			
			if(is_array($value)) {				
				if(!is_numeric($key)) {
					//Billrun_Factory::log()->log("$key : $depth",Zend_Log::DEBUG);
					$retStr .= join(",", array_merge($depthArr,array($key))) . PHP_EOL;
				}
				addArrayToCSV($value, $depth+1);
				continue;
			}
			$line[] = $value;
		}
		$retStr .= join(",",$line) . PHP_EOL;
	}
?>
<?php
echo addArrayToCSV($header);
echo addArrayToCSV($results);
?>
