<<?= "?" ?>xml version="1.0" encoding="UTF-16" ?>
<CallGeneratorReport>
	<From><?= date(Billrun_Base::base_dateformat,$data['from']) ?></From>
	<To><?= date(Billrun_Base::base_dateformat, $data['to']) ?></To>
	<Summary>
		<Missed><?= $data['summary']['missed'] ?></Missed>
		<DurationDifference><?= $data['summary']['duration_diff'] ?></DurationDifference>
		<CallTypes>
			<?php foreach ($data['summary']['calls_types'] as $key => $value) {	?>
				<<?= ucfirst($key) ?>><?= $value ?></<?= ucfirst($key) ?>>
			<?php } ?>
		</CallTypes>
	<Summary>
	<Comparison>
		<?php foreach ($data['cdr_calls_comparison'] as $key => $compr) {	?>
		<CallComparison>
			<CallTime><?= date(Billrun_Base::base_dateformat,$key*2)?></CallTime>
			<Generated>
				<?php if (isset($compr['generated'])) {					
						 foreach ($compr['generated'] as $key => $value) {	?>
						<<?= ucfirst($key) ?>><?= $value ?></<?= ucfirst($key) ?>>
					<?php } 
					} ?>								
			</Generated>
			<CDR>
				<?php if (isset($compr['cdr'])) {
						 foreach ($compr['cdr'] as $key => $value) {	?>
						<<?= ucfirst($key) ?>><?= $value ?></<?= ucfirst($key) ?>>
					<?php } 
					 } ?>
			</CDR>
		</CallComparison>
		<?php } ?>
	</Comparison>
	<CallsBreakdown>
		<?php foreach ($data['generated_breakdown'] as $key => $value) { ?>
			<<?= ucfirst($key) ?>><?= count($value )?></<?= ucfirst($key) ?>>
		<?php } ?>
	</CallsBreakdown>
</CallGeneratorReport>