{
	"CallGeneratorReport" : {
		"From" : "<?= date(Billrun_Base::base_dateformat,$data['from']) ?>" ,
		"To" : "<?= date(Billrun_Base::base_dateformat, $data['to']) ?>",
		"Summary" : {
			"Missed" : "<?= $data['summary']['missed'] ?>",
			"DurationDifference" : "<?= $data['summary']['duration_diff'] ?>",
			"CallTypes" : {
				 <?php foreach ($data['summary']['calls_types'] as $key => $value) {	?>
					"<?= ucfirst($key) ?>" : "<?= $value ?>",
				<?php } ?>
			}
		},
		"Comparison" : {
			<?php foreach ($data['cdr_calls_comparison'] as $key => $value) {	?>
					<?= json_encode($value) ?> 
		<?php } ?>
		}
		
	}
}