# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: docker
stages:
- build
- test
variables:
  GIT_STRATEGY: clone
  GIT_CHECKOUT: 'true'
  GIT_CLEAN_FLAGS: "-ffdx -e .cache"
print-info:
  stage: build
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS ==
      "skip_ci"
  when: manual
  script:
  - 'echo "Job start: $CI_JOB_STARTED_AT"'
  - 'echo "Branch: $CI_COMMIT_BRANCH"'
  - 'echo "Commit Author: $CI_COMMIT_AUTHOR"'
codecept:
  services:
  - name: docker:dind
    alias: dockerhost
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    DOCKER_HOST: tcp://dockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  stage: test
  tags:
  - new_docker_runner
  before_script:
  - mkdir logs cache
  - chmod 777 logs/ cache/
  - cp $TEST_ENV_CODECEPT $CI_PROJECT_DIR/tests/.env
  - cd $CI_PROJECT_DIR/docker/billrun-docker
  - docker-compose -f docker-compose-php74-tests.yml up --wait --build --detach
  script:
  - cd $CI_PROJECT_DIR/docker/billrun-docker/
  - docker exec -w /billrun billrun-app php vendor/bin/codecept build
  - docker exec -w /billrun billrun-app php vendor/bin/codecept run unit
  - docker exec -w /billrun billrun-app php vendor/bin/codecept run functional
  - docker exec -w /billrun billrun-app php vendor/bin/codecept run api
  - docker exec -w /billrun billrun-app php vendor/bin/codecept run acceptance
  - docker exec -w /billrun billrun-app php vendor/bin/codecept run all
  - cd $CI_PROJECT_DIR/docker/billrun-docker
  - docker-compose -f docker-compose-php74-tests.yml down --remove-orphans
build:
  stage: build
  image: docker:20.10.16
  services:
  - docker:dind
  script:
  - echo "Building Docker image from Tag $CI_COMMIT_TAG"
  - docker build -t billrun/billrun:$CI_COMMIT_TAG -f docker/cicd/Dockerfile  .
  - docker images
  rules:
  - if: "$CI_COMMIT_TAG =~ /^5\\.\\d+\\.\\d+(-(beta|rc)\\d+(\\.\\d+)?)?$/"
push:
  stage: build
  image: docker:20.10.16
  services:
  - docker:dind
  script:
  - docker images
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  - docker push billrun/billrun:$CI_COMMIT_TAG
  - docker rmi -f billrun/billrun:$CI_COMMIT_TAG
  needs:
  - build
  rules:
  - if: "$CI_COMMIT_TAG =~ /^5\\.\\d+\\.\\d+(-(beta|rc)\\d+(\\.\\d+)?)?$/"
include:
- template: Jobs/Secret-Detection.gitlab-ci.yml
- template: Security/SAST-IaC.latest.gitlab-ci.yml
