<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title><?php echo $title ?></title>
<script src="<?php echo $baseUrl; ?>/js/vendor/jquery-1.11.0.min.js"></script>
<script src="<?php echo $baseUrl; ?>/js/vendor/bootstrap.js"></script>
<script src="<?php echo $baseUrl; ?>/js/moment.js"></script>
<script src="<?php echo $baseUrl; ?>/js/moment-with-locales.min.js"></script>
<script src="<?php echo $baseUrl; ?>/js/bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo $baseUrl; ?>/js/clipboard.min.js"></script>
<script src="<?php echo $baseUrl; ?>/js/jquery.formautofill.min.js"></script>
<script src="<?php echo $baseUrl; ?>/js/utest/utest.js"></script>
<link rel="stylesheet" href="<?php echo $baseUrl; ?>/css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo $baseUrl; ?>/css/bootstrap.vertical-tabs.min.css">
<link rel="stylesheet" href="<?php echo $baseUrl; ?>/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="<?php echo $baseUrl; ?>/css/main.css">
<link rel="stylesheet" href="<?php echo $baseUrl; ?>/css/utest.css">