<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title><?php echo $title ?></title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="<?php echo $this->subdomain; ?>/js/vendor/jquery-1.11.0.min.js"><\/script>')</script>
<script src="<?php echo $subdomain ?>/js/vendor/bootstrap.js"></script>
<script src="<?php echo $subdomain ?>/js/moment.js"></script>
<script src="<?php echo $subdomain ?>/js/moment-with-locales.min.js"></script>
<script src="<?php echo $subdomain ?>/js/bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo $subdomain ?>/js/clipboard.min.js"></script>
<script src="<?php echo $subdomain ?>/js/utest/utest.js"></script>
<link rel="stylesheet" href="<?php echo $subdomain ?>/css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo $subdomain ?>/css/bootstrap.vertical-tabs.min.css">
<link rel="stylesheet" href="<?php echo $subdomain ?>/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet" href="<?php echo $subdomain ?>/css/main.css">
<link rel="stylesheet" href="<?php echo $subdomain ?>/css/utest.css">