<?php if (!empty($lines['rows'])) : ?>
	<div class="panel panel-default">
		<div class="panel-heading down" data-toggle="collapse" data-target="#lines"><?php echo $lines['ref'] ?>,  SID : <?php echo $sid ?></div>
		<div class="panel-body collapse in" id='lines'>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>#</th>
						<th>URT</th>
						<th>Usage T</th>
						<th>Type</th>
						<th>aPrice</th>
						<th>Usage V</th>
						<th>Balance Before</th>
						<th>Balance After</th>
						<th>aRate ID</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($lines['rows'] as $key => $line) : ?>
						<tr>
							<td><?php echo ($key + 1) ?> </td>
							<td><?php echo $line['time_date'] ?></td>
							<td><?php echo $line['usaget'] ?></td>
							<td><?php echo $line['record_type'] ?> </td>
							<td><?php echo $line['aprice'] ?></td>
							<td><?php echo $line['usagev'] ?></td>
							<td><?php echo $line['balance_before'] ?></td>
							<td><?php echo $line['balance_after'] ?></td>
							<td><a href="<?php echo $this->baseUrl; ?>/admin#/rates/update/<?php echo $line['arate'] ?>" target="_blank"><?php echo $line['arate'] ?></a></td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		<div class="panel-footer"><strong>Total (aprice) : <?php echo $lines['total'] ?></strong></div>
	</div>
<?php endif; ?>