<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
        <div class="navbar-header billrun-logo">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="brand" href="<?php echo $this->baseUrl; ?>/admin">
				<img src="http://www.billrun.net/images/billrun/web-logo.png" alt="BillRun"/>
			</a>
        </div>
		<?php
		print $this->render('layout/menu.phtml', array('active' => 'utest'));
		?>
	</div>
</div>