
<div class="section section-invoice-head">
				<div class="table">
					<table>
						<tbody><tr>
							<td class="page-title"><h3 class="inline">INVOICE</h3></td>
							<td>
								<span class="label">Customer</span>
								<h3 class="inline">David Morison</h3>
							</td>
							<td>
								<span class="label">Invoice#</span>
								<span>100183</span>
							</td>
							<td>
								<span class="label">Period</span>
								<h3 class="inline">October 2016</h3>
							</td>
						</tr>
					</tbody></table>
				</div><!-- /.table -->
			</div>
<div class="section section-invoice-base">
				<h2>Subscriber#1:</h2>
				<h1>Ann morison</h1>
				<p class="label">Description of subscriber if available</p>
			</div>