<div class="section section-invoice-details">
	<div class="section-head">
		<h2 class="section-title">Usage details</h2><!-- /.section-title -->
	</div><!-- /.section-head -->

	<div class="section-body">
		<div class="table table-default">
			<table>
				<thead>
					<tr>
						<th>Date &amp; Time</th>
						<th>Type</th>
						<th>Rate</th>
						<th>Volume</th>
						<th>Amount</th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<td>01/10/2016 08:34</td>
						<td>Service</td>
						<td>Service description &amp; rate</td>
						<td>480 min</td>
						<td>$ 10.00</td>
					</tr>
					<tr>
						<td>01/10/2016 10:05</td>
						<td>Service</td>
						<td>Service description &amp; rate</td>
						<td>-</td>
						<td>$ 6.24</td>
					</tr>
					<tr>
						<td>02/10/2016 00:00</td>
						<td>Plan</td>
						<td>Plan description &amp; rate</td>
						<td>-</td>
						<td>$ 10.00</td>
					</tr>
					<tr>
						<td>03/10/2016 12:15</td>
						<td>Product</td>
						<td>Product description &amp; rate</td>
						<td>500 SMS</td>
						<td>$ 3.50</td>
					</tr>
					<tr>
						<td>05/10/2016 08:34</td>
						<td>Service</td>
						<td>Service description &amp; rate</td>
						<td>30 min</td>
						<td>$ 10.00</td>
					</tr>
					<tr>
						<td>05/10/2016 10:05</td>
						<td>Service</td>
						<td>Service description &amp; rate</td>
						<td>-</td>
						<td>$ 6.24</td>
					</tr>
					<tr>
						<td>06/10/2016 00:00</td>
						<td>Plan</td>
						<td>Plan description &amp; rate</td>
						<td>-</td>
						<td>$ 10.00</td>
					</tr>
					<tr>
						<td>06/10/2016 12:15</td>
						<td>Product</td>
						<td>Product description &amp; rate</td>
						<td>200 SMS</td>
						<td>$ 3.50</td>
					</tr>
				</tbody>
			</table>
		</div><!-- /.table table-default -->
	</div><!-- /.section-body -->
</div>