<div class="section section-invoice-details">
				<div class="section-head">
					<h2 class="section-title">Usage details</h2><!-- /.section-title -->
				</div><!-- /.section-head -->

				<div class="section-body">
					<div class="table table-default table-default-primary">
						<table>
							<thead>
								<tr>
									<th>Description</th>
									<th>Amount</th>
								</tr>
							</thead>
							
							<tbody>
								<tr>
									<td>Premium plan</td>
									<td>$ 20.00</td>
								</tr>
								<tr>
									<td>Services</td>
									<td>$ 0</td>
								</tr>
								<tr class="last">
									<td>Extras</td>
									<td>$ 0.00</td>
								</tr>
								<tr class="total">
									<td>TOTAL</td>
									<td><strong>$ 20.00</strong></td>
								</tr>
								<tr class="total">
									<td>VAT (17%)</td>
									<td>$ 3.40</td>
								</tr>
							</tbody>

							<tfoot>
								<tr class="grand-total">
									<td>GRAND TOTAL</td>
									<td>$ 23.40</td>
								</tr>
							</tfoot>
						</table>
					</div><!-- /.table table-default table-default-primary -->
				</div><!-- /.section-body -->
			</div>