<?php

/**
 * @package         Billing
 * @copyright       Copyright (C) 2012 BillRun Technologies Ltd. All rights reserved.
 * @license         GNU Affero General Public License Version 3; see LICENSE.txt
 */

$entities = current($this->output)['details'];
$headers = $this->output->headers;
$delimiter = $this->output->delimiter;

if (empty($headers) && count($entities) > 0) {
	$headers = array_keys($entities[0]);
}

echo implode($delimiter, $headers) . PHP_EOL;

foreach ($entities as $entity) {
	$line = array();
	foreach ($headers as $header) {
		echo (isset($entity[$header]) ? $entity[$header] : '') . $delimiter;
	}
	echo PHP_EOL;
}
