<?php

/**
 * @package         Billing
 * @copyright       Copyright (C) 2012 BillRun Technologies Ltd. All rights reserved.
 * @license         GNU Affero General Public License Version 3; see LICENSE.txt
 */
$entities = current($this->output)['details'];
$headers = $this->output->headers;
$delimiter = $this->output->delimiter;

if (empty($headers) && count($entities) > 0) {
	$headers = array_keys($entities[0]);
}
if (isset($headers[0])) {
	$headers = array_combine($headers , $headers);
}

header('Content-Encoding: UTF-8');
header('Content-type: text/csv; charset=UTF-8');

$lines = array();
array_push($lines, $headers);
$out = fopen('php://output', 'w');

foreach ($entities as $entity) {
	$line = array();
	foreach (array_keys($headers) as $header) {
		array_push($line, Billrun_Util::getIn($entity, $header, null));
	}
	array_push($lines, $line);
}

foreach ($lines as $line) {
	fputcsv($out, $line);
}
fclose($out);
