

<div class="wrapper">
	<!-- Your header goes here -->
	<div class="main">
		<div class="shell">
			<section class="section">
				<?php
				foreach ($data->get('subs') as $subscriber) {
					$totalForSubscriber = $subscriber['totals']['after_vat'];
					$subscriberUsage = isset($subscriber['breakdown']['usages']) ? $subscriber['breakdown']['usages'] : array();
					if(empty($totalForSubscriber) || empty(round($totalForSubscriber,5)) ) {continue;}
					?>
				<div class="subscriber-wrapper page-break-avoid">
					<div class='table--orange'>
						<table>
							<thead>
								<tr>
									<th class='text--right'>
										<strong>פירוט חשבון <?php echo  empty($subscriber['sid']) ? 'ללקוח' : 'למנוי '. @$subscriber['phone'] ?></strong>
									</th>
								</tr>
							</thead>

							<tbody>
<!--								<tr>
									<td>
										<p><strong>שם <?php echo  empty($subscriber['sid']) ? 'הלקוח' : 'המנוי'?>:  <?php echo $subscriber['firstname'] . ' ' . $subscriber['lastname'] ?> </strong></p>

										<p style="white-space: pre-wrap;"><?php print $this->getPlanDescription($subscriber); ?></p>
									</td>
								</tr>-->
							</tbody>
						</table>
					</div>
					<?php
					$charge = array_filter($subscriberUsage, function($usage) {
						return $usage['name'] == 'one_time_charges';
					});
					$discounts = array_filter($subscriberUsage, function($usage) {
						return $usage['name'] == 'discounts';
					});
					$refunds = array_filter($subscriberUsage, function($usage) {
						return $usage['name'] == 'refunds';
					});

					print $this->render($this->getScriptPath().'/subscriber_details/var_charges.phtml', array('subscriber' => $subscriber));

					if (!empty($charge)) {
						print $this->render($this->getScriptPath() . '/subscriber_details/one_time_charges.phtml', array('subscriber' => $subscriber, 'charge' => current($charge)));
					}

					if (!empty($discounts)) {
						print $this->render($this->getScriptPath() . '/subscriber_details/discounts.phtml', array('subscriber' => $subscriber, 'discounts' => current($discounts)));
					}

					if (!empty($refunds)) {
						print $this->render($this->getScriptPath() . '/subscriber_details/refunds.phtml', array('subscriber' => $subscriber, 'refunds' => current($refunds)));
					}
					?>

					<div class="section__group">
						<div class="table table--secondary col--4 subscriber-total">
							<table>
								<tfoot>
									<tr>
										<td></td>

										<td></td>

										<td>
											<p>
												<strong>
													סה״כ <br> כולל מע״מ
												</strong>
											</p>
										</td>

										<td>
											<div class="buble buble--small orange">
												<p class='number'><?php echo $this->getFormatedPrice($totalForSubscriber); ?></p>
											</div><!-- /.buble -->
										</td>
									</tr>
								</tfoot>


							</table>
						</div><!-- /.table-/-secondary -->
					</div>
				</div>	
				<?php } ?>
			</section><!-- /.section -->
		</div><!-- /.shell -->
	</div><!-- /.main -->

	<!-- Your footer goes here -->

</div><!-- /.wrapper -->

<script src=<?php echo $this->getScriptPath() . "/assets/js/bundle.js" ?>></script>
