Are you sure you want to remove <?php echo $this->key; ?>?
<?php
print '<div class="form_protect">';
print '<span id="form_id" class="hidden">' . $this->id . '</span>';
print '<span id="form_type" class="hidden">' . $this->type . '</span>';
print '<span id="form_coll" class="hidden">' . $this->collectionName . '</span>';
print '</div>';
?>
<script type="text/javascript">
	$('#confirm').click(function confirmClick() {
		$(this).attr('disabled', 'disabled');
		$(this).unbind("click", confirmClick);
		var _ajaxOpts = {
			async:true,
			cache:false,
			//			dataType:'json',
			type:'POST',
			data: {
				id: $('#form_id').html(),
				coll: $('#form_coll').html(),
				type: $('#form_type').html(),
			},
			success:function(data, textStatus, jqXHR) {
				if (data!='null') {
					alert(data);
					$('#confirm').removeAttr("disabled");
					$('#confirm').bind("click", confirmClick);
					return;
				}
				window.location.reload();
			},
			error:function(jqXHR, textStatus, errorThrown) {
				alert('some error occured');
			}
		};
		$.ajax('<?php echo $this->baseUrl; ?>/admin/remove', _ajaxOpts);
	});
</script>