<div class="container component">

	<h2>Configuration</h2>
	<form id="config-form">
		<div class="clearfix config">
			<div class="option">
				<span>Receive</span>
				<input type="checkbox" name="receive" checked>
			</div>
			
			<div class="option">
				<span>Process</span>
				<input type="checkbox" name="process" checked>
			</div>

			<div class="option">
				<span>Calculate</span>
				<input type="checkbox" name="calculate" checked>
			</div>
		</div>
		<div class="submit">
			  <button type="submit" class="btn">Submit</button>
		</div>
		
	</form>
	<hr>

	<footer>
		<p>&copy; S.D.O.C. LTD 2012-2014</p>
	</footer>

</div> <!-- /container -->
