<?php // print_R($this->data); die; ?>
<div class="container component">

	<h2>Configuration</h2>
	<form id="config-form" action="/admin/configsave">
		<div class="clearfix config">
			<?php 
			foreach ($this->options as $action) : ?>
			<div class="option">
				<span><?php echo ucfirst($action) ?></span>
				<input type="checkbox" name="receive" value="1"<?php
					echo (isset($this->data[$action]) && $this->data[$action])?' checked': ''; ?>>
			</div>
			 <?php endforeach; ?>
					</div>
		<div class="submit">
			  <button type="submit" class="btn">Submit</button>
		</div>
		
	</form>
	<hr>

	<footer>
		<p>&copy; S.D.O.C. LTD 2012-2014</p>
	</footer>

</div> <!-- /container -->
