<div class="toolbar">
	<form action="" method="post" class="form-horizontal">
		<?php if (strtolower($this->title)=='lines') : ?>
		<label class="checkbox">
			<input name="garbage" type="checkbox">Garbage lines
		</label>
		<span><button type="submit" class="btn">Search</button></span>
		<?php endif; ?>
		<script type="text/javascript">
			var edit_url_prefix = <?php echo json_encode($this->baseUrl . '/admin/edit?coll=' . strtolower($this->title) . '&id='); ?>;
			var confirm_url_prefix = <?php echo json_encode($this->baseUrl . '/admin/confirm?coll=' . strtolower($this->title) . '&id='); ?>;
		</script>
		<?php if (strtolower($this->title)=='lines') : ?>
		<span><a id='update_current' data-type="update" href="#popupModal" class="btn btn-warning" data-toggle="modal" role="button" data-remote="">Update current</a></span>
		<span><a id='remove' data-type="remove" href="#confirmModal" class="btn btn-danger" data-toggle="modal" role="button" data-remote=""><i class="icon-remove"> </i>Remove</a></span>
		<?php endif; ?>
	</form>
</div>