<div class="component container">

	<!-- Main hero unit for a primary marketing message or call to action -->
	<div class="jumbotron hero-unit">
		<h1>BillRun!</h1>
		<p>The powerful Billing system.</p>
		<p><a href="http://billrun.net" target="_blank" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
	</div>

    <div class="container">
		<!-- Example row of columns -->
		<!--      <div class="row">
				<div class="col-md-4">
				  <h2>Lines</h2>
				  <p>This section help you to manage the lines received to the system, monitor and update them.</p>
				  <p><a class="btn btn-default" href="<?php echo $this->baseUrl; ?>/admin/lines" role="button">View details &raquo;</a></p>
				</div>
				<div class="col-md-4">
				  <h2>Plans</h2>
				  <p>This section help you to manage the plans in the system. You can change the each plan configuration, flat rate and more.</p>
				  <p><a class="btn btn-default" href="<?php echo $this->baseUrl; ?>/admin/plans" role="button">View details &raquo;</a></p>
			   </div>
				<div class="col-md-4">
				  <h2>Rates</h2>
				  <p>This section help you to manage the rates in the system. You can change rate parameters, zones association, price and more.</p>
				  <p><a class="btn btn-default" href="<?php echo $this->baseUrl; ?>/admin/rates" role="button">View details &raquo;</a></p>
				</div>
			  </div>-->

		<hr>

		<footer>
			<?php $this->display('billrun.phtml', array()); ?>
		</footer>

	</div> <!-- /container -->
</div> <!-- /component -->