        <div class="container">

            <!-- Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
                <h1>BillRun!</h1>
                <p>The powerful Billing system.</p>
                <p><a href="http://billrun.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
            </div>

            <div class="row">
                <div class="span4">
                    <h2>Lines</h2>
                    <p>This section help you to manage the lines received to the system, monitor and update them. </p>
                    <p><a class="btn" href="#">View details &raquo;</a></p>
                </div>
                <div class="span4">
                    <h2>Plans</h2>
                    <p>This section help you to manage the plans in the system. You can change the each plan configuration, flat rate and more. </p>
                    <p><a class="btn" href="<?php echo $this->base_url; ?>/admin/plans">View details &raquo;</a></p>
               </div>
                <div class="span4">
                    <h2>Rates</h2>
                    <p>This section help you to manage the rates in the system. You can change rate parameters, zones association, price and more. </p>
                    <p><a class="btn" href="<?php echo $this->base_url; ?>/admin/rates">View details &raquo;</a></p>
                </div>
            </div>

            <hr>

            <footer>
                <p>&copy; S.D.O.C. LTD 2012-2013</p>
            </footer>

        </div> <!-- /container -->
