<div class="container component">

	<!-- Main hero unit for a primary marketing message or call to action -->
	<div class="hero-unit">
		<h1>Call Generator</h1>
		<p>Generating  calls so you don't have to.</p>
		<p><a href="http://billrun.net" target="_blank" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
	</div>

	<div class="row">
		<div class="span4" id="tests">
			<h2>Tests</h2>
			<p>This section help you to manage the lines received to the system, monitor and update them. </p>
			<p><div class="summary"><?php print $this->data['summary']?> </div></p>
			<p><a class="btn" href="<?php echo $this->baseUrl; ?>/admin/tests">View details &raquo;</a></p>
		</div>
		<div class="span4" id="stats">
			<h2>Reports</h2>
			<p>This section help you to manage the plans in the system. You can change the each plan configuration, flat rate and more. </p>
			<p><div class="summary"><?php print $this->data['summary']?> </div></p>
			<p><a class="btn" href="<?php echo $this->baseUrl; ?>/admin/report">View details &raquo;</a></p>
		</div>
	</div>

	<hr>

	<footer>
		<p>&copy; S.D.O.C. LTD 2012-2013</p>
	</footer>

</div> <!-- /container -->
