<div class="login">
	<div class="center">
		<form role="form" class="navbar-form" method="POST" action="login">
			<div class="form-group">
				<input id="username" type="text" class="form-control" placeholder="Username" name="username">
			</div>
			<div class="form-group">
				<input id="password" type="password" class="form-control" placeholder="Password" name="password">
			</div>
			<input class="span1" id="ret_action" name="ret_action" type="hidden" value="<?php echo $this->ret_action; ?>">
			<button class="btn btn-success" type="submit">Sign in</button>
		</form>
	</div>
</div>
