<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h3 id="popupModalLabel"><?php echo AdminController::authorized('write')?'MEdit' : 'MView'; ?> item</h3>
</div>
<div class="modal-body"><?php
$protected = array();
	$entity = $this->entity->getRawData();

	foreach ($this->protectedKeys as $key) {
		if (isset($entity[$key])) {
			$protected[$key] = $entity[$key];
			unset($entity[$key]);
		}
	}
	foreach ($this->hiddenKeys as $key) {
		unset($entity[$key]);
	}

print '<div class="form_protect">';
if (isset($protected['log_stamp'])) {
	$log_stamp = $protected['log_stamp'];
}
foreach ($protected as $k => $v) {
	print '<span class="label label-info">' . $k . '</span>';
	if ($k == "file") {
		print '<a href="#LogPopup" data-toggle="modal" data-remote=""><span id="form' . $k . '"class="label label-inverse">' . $v . '</span></a><br />';
	} else {
		print '<span id="form' . $k . '"class="label label-inverse">' . $v . '</span><br />';
	}
}
print '<span id="form_type" class="hidden">' . $this->type . '</span>';
print '<span id="form_coll" class="hidden">' . $this->collectionName . '</span>';
print '</div>';
?>
<form class='form-inline'>
	<h3>Call</h3>
	<label for='rate-call-access'>Access</label>
	<input type='number' class='form-control' id='rate-call-access' value='<?php echo $entity['rates']['call']['access'] ?>' />
	<label for='rate-unit'>Unit</label>
	<?php $availableCallUnits = array('seconds', 'minutes', 'hours');  ?>
	<select class='form-control' id='rate-call-unit'>
		<?php
		foreach($availableCallUnits as $unit) {
			$selected = ($entity['rates']['call']['unit'] == $unit) ? " selected " : "";
			print "<option value='$unit' $selected>$unit</option>";
		}
		?>
	</select>
	
	<h4>
		Rates
		<small><i id='add-call-rate' class='glyphicon glyphicon-plus-sign' style='color: green; cursor: pointer'></i></small>
	</h4>
	<div id='call-rates'>
		<table class='table table-striped call-rates-table'>
			<thead>
				<tr>
					<th>Interval</th>
					<th>Price</th>
					<th>To</th>
				</tr>
			</thead>
			<tbody id='call-rates-tbody'>
	<?php foreach($entity['rates']['call']['rate'] as $rate) { ?>
				<tr>
		<?php print "<td><input type='number' value='" . $rate['interval'] . "' class='form-control rate-call-interval' /></td>"; ?>
		<?php print "<td><input type='number' value='" . $rate['price'] . "' class='form-control rate-call-price' /></td>"; ?>
		<?php print "<td><input type='number' value='" . $rate['to'] . "' class='form-control rate-call-to' /></td>"; ?>		
				</tr>
	<?php } ?>
			</tbody>
		</table>
		<h4>
			Plans
			<small><i id='add-call-plan' class='glyphicon glyphicon-plus-sign' style='color: green; cursor: pointer'></i></small>
		</h4>
		<div id='rate-call-plans'>
			<?php $availablePlans = array("ACCOUNT_OPTIONS_CONTAINER"); ?>
			<?php foreach($entity['rates']['call']['plans'] as $plan) { ?>
			<select class='form-control rate-call-plan'>
				<?php foreach($availablePlans as $availablePlan) {
					$selected = $availablePlan === $plan ? "selected" : "";
					print "<option id='$availablePlan' value='$availablePlan' $selected >$availablePlan</option>";
				} ?>
			</select>
			<?php } ?>
		</div>
	</div>
	
	<hr/>

	<h3>SMS</h3>
	<label for='rate-sms-category'>Category</label>
	<input type='text' class='form-control' id='rate-sms-category' value='<?php echo $entity['rates']['sms']['category'] ?>' />
	<label for='rate-unit'>Unit: </label> <input type='text' disabled id='rate-sms-unit' value='counter' />

	<h4>
		Rates
		<small><i id='add-sms-rate' class='glyphicon glyphicon-plus-sign' style='color: green; cursor: pointer'></i></small>
	</h4>
	<div id='sms-rates'>
		<table class='table table-striped sms-rates-table'>
			<thead>
				<tr>
					<th>Interval</th>
					<th>Price</th>
					<th>To</th>
				</tr>
			</thead>
			<tbody id='sms-rates-tbody'>		
	<?php foreach($entity['rates']['sms']['rate'] as $rate) { ?>
				<tr>
		<?php print "<td><input type='number' value='" . $rate['interval'] . "' class='form-control rate-sms-interval' /></td>"; ?>
		<?php print "<td><input type='number' value='" . $rate['price'] . "' class='form-control rate-sms-price' /></td>"; ?>
		<?php print "<td><input type='number' value='" . $rate['to'] . "' class='form-control rate-sms-to' /></td>"; ?>
				</tr>
	<?php } ?>
			</tbody>
		</table>
		<h4>
			Plans
			<small><i id='add-sms-plan' class='glyphicon glyphicon-plus-sign' style='color: green; cursor: pointer'></i></small>
		</h4>
		<div id='rate-sms-plans'>
			<?php $availablePlans = array("ACCOUNT_OPTIONS_CONTAINER"); ?>
			<?php foreach($entity['rates']['sms']['plans'] as $plan) { ?>
			<select class='form-control rate-sms-plan'>
				<?php foreach($availablePlans as $availablePlan) {
					$selected = $availablePlan === $plan ? "selected" : "";
					print "<option id='$availablePlan' value='$availablePlan' $selected >$availablePlan</option>";
				} ?>
			</select>
			<?php } ?>
		</div>
	</div>
	
	<hr/>

		<h3>
			Out Circuit Group
			<small><i id='add-out-circuit-group' class='glyphicon glyphicon-plus-sign' style='color: green; cursor: pointer'></i></small>
		</h3>
	<div id='rate-out-circuit-groups'>
		<?php 
		foreach($entity['params']['out_circuit_group'] as $index => $out_circuit_group) {
			print "<div class='rate-out-circuit-group'>";
			print "<label for='out-circuit-group-$index-from'>From:</label>";
			print "<input type='number' class='form-control rate-out-circuit-group-from' id='out-circuit-group-$index-from' value='" . $out_circuit_group['from'] . "' />";
			print "<label for='out-circuit-group-$index-to'>To:</label>";
			print "<input type='number' class='form-control rate-out-circuit-group-to' id='out-circuit-group-$index-to' value='" . $out_circuit_group['to'] . "' />";
			print "</div>";
		}
		?>
	</div>

		<h3>
			Prefix
			<small><i id='add-prefix' class='glyphicon glyphicon-plus-sign' style='color: green; cursor: pointer'></i></small>
		</h3>
	<div id='rate-prefixes'>
<?php
foreach($entity['params']['prefix'] as $prefix) {
	print "<input type='number' class='form-control rate-prefix' value='$prefix' />";
}
?>
	</div>

	
	<h3>
		Record Types
		<small><i id='add-record-type' class='glyphicon glyphicon-plus-sign' style='color: green; cursor: pointer'></i></small>
	</h3>
	<div id='rate-record-types'>
<?php
foreach($entity['params']['record_type'] as $record_type) {
	print "<input type='text' class='form-control rate-record-type' value='$record_type' />";
}
?>
	</div>
</form>
	
<script type="text/javascript">
	var newOutCircuitGroupIndex = 0;
	var newCallRateIndex = 0;
	var newSMSRateIndex = 0;
	var availableOptions = [<?php foreach($availablePlans as $availablePlan) { echo "\"$availablePlan\","; } ?>];

	$('#add-prefix').on('click', function () {
		$('#rate-prefixes').append("<input type='number' class='form-control rate-prefix' />");
	});
	$('#add-record-type').on('click', function () {
		$('#rate-record-types').append("<input type='text' class='form-control rate-record-type' />");
	});
	$('#add-out-circuit-group').on('click', function () {
		newOutCircuitGroupIndex++;
		var new_out_circuit_group = $("<div class='form-group'><label for='out-circuit-group-" + newOutCircuitGroupIndex + "-from'>From:</label>\
<input type='number' class='form-control rate-out-circuit-group-from' id='out-circuit-group-" + newOutCircuitGroupIndex + "-from' />\
<label for='out-circuit-group-" + newOutCircuitGroupIndex + "-to'>To:</label>\
<input type='number' class='form-control rate-out-circuit-group-to' id='out-circuit-group-" + newOutCircuitGroupIndex + "-to' /></div>");
		$('#rate-out-circuit-groups').prepend(new_out_circuit_group);
	});
	
	$('#add-call-rate').on('click', function () {
		newCallRateIndex++;
		var newCallRate = $("<tr><td><input type='number' id='call-rate-" + newCallRateIndex + "-interval' class='form-control rate-call-interval' /></td>\
		<td><input type='number' id='call-rate-" + newCallRateIndex + "-price' class='form-control rate-call-price' /></td>\
		<td><input type='number' id='call-rate-" + newCallRateIndex + "-to' class='form-control rate-call-to' /></td></tr>");
		$('#call-rates-tbody').append(newCallRate);
	});
	$('#add-call-plan').on('click', function () {
		var newCallPlanSelect = $("<select class='form-control rate-call-plan'></select>");
		var newCallPlanOption;
		$.each(availableOptions, function (i, opt) {
			newCallPlanOption = $("<option>" + opt + "</option>");
			newCallPlanOption.attr('id', opt);
			newCallPlanOption.val(opt);
			$(newCallPlanSelect).append(newCallPlanOption);
		});
		$('#rate-call-plans').append(newCallPlanSelect);
	});
	$('#add-sms-plan').on('click', function () {
		var newCallPlanSelect = $("<select class='form-control rate-sms-plan'></select>");
		var newCallPlanOption;
		$.each(availableOptions, function (i, opt) {
			newCallPlanOption = $("<option>" + opt + "</option>");
			newCallPlanOption.attr('id', opt);
			newCallPlanOption.val(opt);
			$(newCallPlanSelect).append(newCallPlanOption);
		});
		$('#rate-sms-plans').append(newCallPlanSelect);
	});
	
	$('#add-sms-rate').on('click', function () {
		newSMSRateIndex++;
		var newSMSRate = $("<tr><td><input type='number' id='sms-rate-" + newSMSRateIndex + "-interval' class='form-control rate-sms-interval' /></td>\
		<td><input type='number' id='sms-rate-" + newSMSRateIndex + "-price' class='form-control rate-sms-price' /></td>\
		<td><input type='number' id='sms-rate-" + newSMSRateIndex + "-to' class='form-control rate-sms-to' /></td></tr>");
		$('#sms-rates-tbody').append(newSMSRate);
	});
	
	var entityJson = <?php echo json_encode($entity); ?>;
	console.log(entityJson);
	var _jsonData = entityJson;
	var opt = {
		change: function(data) {
			/* called on every change */
			_jsonData = data;
		},
		propertyclick: function(path) { /* called when a property is clicked with the JS path to that property */
			jsonPath = JSON.parse(path);
			var protectedKeys = <?php echo json_encode($this->protectedKeys); ?>;
			for (p in jsonPath) {
				if ($.inArray(jsonPath[p], protectedKeys) !== -1) {
					$('input[title="' + jsonPath[p] + '"]').attr('disabled', 'disabled');
				}
			}
		}
	};
	/* opt.propertyElement = '<textarea>'; */ // element of the property field, <input> is default
	/* opt.valueElement = '<textarea>'; */  // element of the value field, <input> is default
	//var _jsonEditor = $('#jsondiv').jsonEditor(entityJson, opt);
	$('#save').unbind();
	$('#save').removeAttr("disabled");
	$('#save').click(function saveClick() {
		/*
		$(this).attr('disabled', 'disabled');
		$(this).unbind("click", saveClick);
		*/
	   var call_rates = [];
	   var cur = {};
		$('#call-rates-tbody tr').each(function (i, rate) { 
			cur.interval = $('.rate-call-interval', rate).val();
			cur.price = $('.rate-call-price', rate).val();
			cur.to = $('.rate-call-to', rate).val();
			call_rates.push(cur);
			cur = {};
		});
	   var sms_rates = [];
	   cur = {};
		$('#sms-rates-tbody tr').each(function (i, rate) { 
			cur.interval = $('.rate-sms-interval', rate).val();
			cur.price = $('.rate-sms-price', rate).val();
			cur.to = $('.rate-sms-to', rate).val();
			sms_rates.push(cur);
			cur = {};
		});		
		
		var out_circuit_group = [];
		cur = {};
		$('.rate-out-circuit-group').each(function (i, group) {
			cur.from = $('.rate-out-circuit-group-from', group).val();
			cur.to = $('.rate-out-circuit-group-to', group).val();
			out_circuit_group.push(cur);
			cur = {};
		});
		
		var prefixes = [];
		$('.rate-prefix').each(function (i, prefix) {
			prefixes.push($(prefix).val());
		});
		
		var record_types = [];
		$('.rate-record-type').each(function (i, record_type) {
			record_types.push($(record_type).val());
		});
		var call_plans = [];
		$('.rate-call-plan').each(function (k, plan) {
			call_plans.push($(plan).val());
		});
		var sms_plans = [];
		$('.rate-sms-plan').each(function (k, plan) {
			sms_plans.push($(plan).val());
		});
		var data = {
			params: {
				out_circuit_group: out_circuit_group,
				prefix: prefixes,
				record_type: record_types
			},
			rates: {
				call: {
					access: $('#rate-call-access').val(),
					unit: $('#rate-call-unit').val(),
					category: $('#rate-call-category').val(),
					rate: call_rates,
					plans: call_plans
				},
				sms: {
					access: $('#rate-sms-access').val(),
					unit: $('#rate-sms-unit').val(),
					category: $('#rate-sms-category').val(),
					rate: sms_rates,
					plans: sms_plans
				}
			}
		};
		var _ajaxOpts = {
			async: true,
			cache: false,
			//			dataType:'json',
			type: 'POST',
			data: {
				id: $('#form_id').html(),
				coll: $('#form_coll').html(),
				type: $('#form_type').html(),
				duplicate_rates: $('#duplicate_rates').is(':checked'),
				data: JSON.stringify(data)
			},
			success: function(data, textStatus, jqXHR) {
				if (data != 'null') {
					alert(data);
					$('#save').removeAttr("disabled");
					$('#save').bind("click", saveClick);
					return;
				}
				window.location.reload();
			},
			error: function(jqXHR, textStatus, errorThrown) {
				alert('some error occured');
			}
		};
		$.ajax('<?php echo $this->baseUrl; ?>/admin/save', _ajaxOpts);
	});

	$('#formfile').click(function() {
		if ($('#formfile').html().length) {
			$('#formfile').parent().data('remote', '<?php echo $this->baseUrl; ?>/admin/logDetails?type=logDetails&coll=log&stamp=' + $('#formlog_stamp').html());
		}
	});
</script>
<div class="modal-footer">
	<?php if ($this->collectionName == 'plans' && $this->type == 'duplicate') : ?>
	<div class="edit_checkboxes">
	<input class="span1" id="duplicate_rates" name="duplicate_rates" type="checkbox" value="on" checked> <label class="span1" for="duplicate_rates">Duplicate rates</label>
	</div>
	<?php endif; ?>
	<button id="cancelPopup" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	<?php if (AdminController::authorized('write')) : ?>
	<button id="save" class="btn btn-primary">Save changes</button>
	<?php endif; ?>
</div>