<style>
	.glyphicon-minus-sign {
		color: #bc2328;
		cursor: pointer;
	}
	.glyphicon-plus-sign {
		color: green;
		cursor: pointer;
	}
	#plan-include-groups-div {
		margin-top: 15px;
	}
	.glyphicon-chevron-right,
	.glyphicon-chevron-down,
	.group-name,
	.h4, .h3 {
		cursor: pointer;
	}
	table {
		margin-top: 10px;
	}
</style>

<?php
$protected = array();
	$entity = $this->data['entity']->getRawData();
	foreach ($this->data['protectedKeys'] as $key) {
		if (isset($entity[$key])) {
			$protected[$key] = $entity[$key];
			unset($entity[$key]);
		}
	}
	foreach ($this->data['hiddenKeys'] as $key) {
		unset($entity[$key]);
	}
?>

<script>
	var entity = <?php echo json_encode($this->data['entity']->getRawData()); ?>;
	var form_data = <?php echo json_encode($this->data); ?>;
</script>
<script src='<?php echo $this->baseUrl; ?>/js/controllers/PlansController.js'></script>
<div class="container component" ng-controller='PlansController'>

<?php
	print '<div class="form_protect">';
if (isset($protected['log_stamp'])) {
	$log_stamp = $protected['log_stamp'];
}
foreach ($protected as $k => $v) {
	print '<span class="label label-info">' . $k . '</span>';
	if ($k == "file") {
		print '<a href="#LogPopup" data-toggle="modal" data-remote=""><span id="form' . $k . '"class="label label-inverse">' . $v . '</span></a><br />';
	} else {
		print '<span id="form' . $k . '"class="label label-inverse">' . $v . '</span><br />';
	}
}
print '<span id="form_type" class="hidden">' . $this->data['type'] . '</span>';
print '<span id="form_coll" class="hidden">' . $this->data['collectionName'] . '</span>';
print '</div>';
?>
<form class='form-inline' ng-submit='savePlan()'>
	<table class='table table-striped table-bordered'>
		<thead>
			<tr>
				<th>Price</th>
				<th>Vatable</th>
				<th>To</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><input ng-model='entity.price' type='text' id='plan-price' class='form-control' /></td>
				<td><input ng-model='entity.vatable' type="checkbox" id="plan-vatable" class="form-control" /></td>
				<td><input ng-model='entity.to' type='text' id='plan-to' disabled /></td>
			</tr>
		</tbody>
	</table>

	<hr/>
	
	<i class='glyphicon glyphicon-chevron-right' ng-hide='shown.include' ng-click='shown.include = !shown.include'></i>
	<i class='glyphicon glyphicon-chevron-down' ng-show='shown.include' ng-click='shown.include = !shown.include'></i>
	<span class='h3' ng-click='shown.include = !shown.include'>
		Include
	</span>
	<select id='new-include-type' class='form-control' ng-model='newIncludeType'>
		<option ng-repeat='type in includeTypes' ng-disabled="entity.include[type]">{{type}}</option>
	</select>
	<input ng-model='newIncludeValue' type='text' class='form-control' ng-disabled='newIncludeType == "groups"' />
	<i id='add-plan-include' class='glyphicon glyphicon-plus-sign' ng-click='addPlanInclude()'></i>
	<ul>
	<div id='plan-includes' ng-show='shown.include'>
		<div ng-if='entity.include.call'>
			<h4>
				Call
				<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteInclude("call")'></i></small>				
			</h4>
			<input ng-model='entity.include.call' type='text' class='plan-include form-control' />
		</div>

		<div ng-if='entity.include.data'>
			<h4>
				Data
				<small><i class='delete-plan glyphicon glyphicon-minus-sign'  ng-click='deleteInclude("data")'></i></small>				
			</h4>
			<input ng-model='entity.include.data' type='text' class='plan-include form-control' />
		</div>

		<div ng-if='entity.include.mms'>
			<h4>
				MMS
				<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteInclude("mms")'></i></small>				
			</h4>
			<input ng-model='entity.include.mms' type='text' class='plan-include form-control' />
		</div>

		<div ng-if='entity.include.sms'>
			<h4>
				SMS
				<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteInclude("sms")'></i></small>				
			</h4>
			<input ng-model='entity.include.sms' type='text' class='plan-include form-control' />
		</div>

		<div id='plan-include-groups-div' ng-if='entity.include.groups'>
			<i class='glyphicon glyphicon-chevron-right' ng-hide='shown.groups' ng-click='shown.groups = !shown.groups'></i>
			<i class='glyphicon glyphicon-chevron-down' ng-show='shown.groups' ng-click='shown.groups = !shown.groups'></i>
			<span class='h4' ng-click='shown.groups = !shown.groups'>Groups</span>
			<input ng-model='newGroup.name' type='text' class='form-control' />
			<i class='add-group glyphicon glyphicon-plus-sign' ng-click="addNewGroup()"></i>
			<ul>
				<div style='margin-top: 15px; margin-bottom: 15px' class='plan-include-group' ng-show='shown.groups'
					 ng-repeat='(group_name, group_data) in entity.include.groups'>
					<!--<input ng-model='group_name' type='text' class='form-control include-group-name' />-->
					<i class='glyphicon glyphicon-chevron-right' ng-hide='shownGroups[group_name]' ng-click='shownGroups[group_name] = !shownGroups[group_name]'></i>
					<i class='glyphicon glyphicon-chevron-down' ng-show='shownGroups[group_name]' ng-click='shownGroups[group_name] = !shownGroups[group_name]'></i>
					<span ng-click='shownGroups[group_name] = !shownGroups[group_name]' class='group-name'>{{group_name}}</span>
					<i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroup(group_name)'></i>
					<select class='plan-param-type form-control' ng-model='newParamType[group_name]'>
						<option ng-repeat='param in groupParams' ng-disabled="entity.include.groups[group_name][param]">{{param}}</option>
					</select>
					<input type='text' class='form-control' ng-model='newParamValue[group_name]' />
					<i class="add-plan-param glyphicon glyphicon-plus-sign" ng-click='addGroupParam(group_name)'></i>
					<br/>
					<ul ng-show='shownGroups[group_name]'>
						<div id='include-group-limits-div' ng-if='group_data.limits'>
							Limits: <small>(edit enabled in advanced mode)</small>
							<input ng-model='group_data.limits' type='text' class='form-control group-param' disabled />
							<i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "limits")'></i>
						</div>

						<div id='include-group-rule-div' ng-if='group_data.rule'>
							Rule: <small>(edit enabled in advanced mode)</small>
							<input ng-model='group_data.rule' type='text' class='form-control group-param' disabled />
							<i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "rule")'></i>
						</div>

						<div id='include-group-data-div' ng-if='group_data.data'>
							Data: <input ng-model='group_data.data' type='text' class='form-control group-param' />
							<i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "data")'></i>
						</div>

						<div id='include-group-call-div' ng-if='group_data.call'>
							Call: <input ng-model='group_data.call' type='text' class='form-control group-param' />
							<i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "call")'></i>
						</div>

						<div id='include-group-incoming-call-div' ng-if='group_data.incoming_call'>
							Incoming Call: <input ng-model='group_data.incoming_call' type='text' class='form-control group-param' />
							<i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "incoming_call")'></i>
						</div>

						<div id='include-group-incoming-sms-div' ng-if='group_data.incoming_sms'>
							Incoming SMS: <input ng-model='group_data.incoming_sms' type='text' class='form-control group-param' />
							<i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "incoming_sms")'></i>
						</div>

						<div id='include-group-sms-div' ng-if='group_data.sms'>
							SMS: <input ng-model='group_data.sms' type='text' class='form-control group-param' />
							<i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "sms")'></i>
						</div>
					</ul>
				</div>
			</ul>
		</div>
	</div>
	</ul>	
	<div class="modal-footer">
		<?php if ($this->collectionName == 'plans' && $this->type == 'duplicate') : ?>
		<div class="edit_checkboxes">
		<input class="span1" id="duplicate_rates" name="duplicate_rates" type="checkbox" value="on" checked> <label class="span1" for="duplicate_rates">Duplicate rates</label>
		</div>
		<?php endif; ?>
		<button id="cancel" ng-click='cancel()' class="btn" aria-hidden="true">Close</button>
		<?php if (AdminController::authorized('write')) : ?>
		<button type='submit' class="btn btn-primary">Save changes</button>
		<?php endif; ?>
	</div>
	</form>
</div>