<style>
	.glyphicon-minus-sign {
		color: #bc2328;
		cursor: pointer;
	}
	.glyphicon-plus-sign {
		color: green;
		cursor: pointer;
	}
	#plan-include-groups-div {
		margin-top: 15px;
	}
	table {
		margin-top: 10px;
	}
</style>

<?php
$protected = array();
	$entity = $this->data['entity']->getRawData();
	foreach ($this->data['protectedKeys'] as $key) {
		if (isset($entity[$key])) {
			$protected[$key] = $entity[$key];
			unset($entity[$key]);
		}
	}
	foreach ($this->data['hiddenKeys'] as $key) {
		unset($entity[$key]);
	}
?>

<script>
	var entity = <?php echo json_encode($this->data['entity']->getRawData()); ?>;
	var form_data = <?php echo json_encode($this->data); ?>;
</script>
<script src='<?php echo $this->baseUrl; ?>/js/controllers/PlansController.js'></script>
<div class="container component" ng-controller='PlansController'>
	<center>
		<h2>{{entity.name}}</h2>
	</center>
<form class='form-inline' ng-submit='savePlan()'>
	<div class="row">
		<div class="col-md-2">Price</div>
		<div class="col-md-6"><input ng-model='entity.price' type='text' id='plan-price' class='form-control' /></div>
	</div>
	<div class="row">
		<div class="col-md-2">Vatable</div>
		<div class="col-md-6"><input ng-model='entity.vatable' type="checkbox" id="plan-vatable" class="form-control" /></div>
	</div>
	<div class="row">
		<div class="col-md-2">To</div>
		<div class="col-md-6"><input ng-model='entity.to' type='text' id='plan-to' disabled /></div>
	</div>

	<hr/>
	
	<h3>Customer Plan Include</h3>
	<div id='plan-includes'>
		<div ng-if='entity.include.call !== undefined'>
			<div class="row">
				<div class="col-md-2">
					<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteInclude("call")'></i></small>
					Call
				</div>
				<div class="col-md-6">
					<input ng-model='entity.include.call' type='text' class='plan-include form-control' />
				</div>
			</div>
		</div>

		<div ng-if='entity.include.data !== undefined'>
			<div class="row">
				<div class="col-md-2">
					<small><i class='delete-plan glyphicon glyphicon-minus-sign'  ng-click='deleteInclude("data")'></i></small>
					Data
				</div>
				<div class="col-md-6">
					<input ng-model='entity.include.data' type='text' class='plan-include form-control' />
				</div>
			</div>
		</div>

		<div ng-if='entity.include.mms !== undefined'>
			<div class="row">
				<div class="col-md-2">
					<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteInclude("mms")'></i></small>				
					MMS
				</div>
				<div class="col-md-6">
					<input ng-model='entity.include.mms' type='text' class='plan-include form-control' />
				</div>
			</div>
		</div>

		<div ng-if='entity.include.sms !== undefined'>
			<div class="row">
				<div class="col-md-2">
					<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteInclude("sms")'></i></small>
					SMS
				</div>
				<div class="col-md-6">
					<input ng-model='entity.include.sms' type='text' class='plan-include form-control' />
				</div>
			</div>
		</div>
		
		<div class='row'>
			<div class='col-md-2'>
				<select id='new-include-type' class='form-control' ng-model='newInclude.type'>
					<option ng-repeat='type in includeTypes' ng-disabled="entity.include[type]">{{type}}</option>
				</select>
			</div>
			<div class='col-md-6'>
				<input ng-model='newInclude.value' type='text' class='form-control' ng-disabled='!newInclude.type' />
				<i id='add-plan-include' class='glyphicon glyphicon-plus-sign' ng-click='addPlanInclude()'></i>
			</div>
		</div>
	</div>
	
	<hr/>		
	
	<div id='plan-include-groups-div'>
		<h3>Groups</h3>
		<input ng-model='newGroup.name' type='text' class='form-control' />
		<i class='add-group glyphicon glyphicon-plus-sign' ng-click="addNewGroup()"></i>
		<div style='margin-top: 15px; margin-bottom: 15px' class='plan-include-group'
			 ng-repeat='(group_name, group_data) in entity.include.groups'>
			<h4>
				<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroup(group_name)'></i></small>
				{{group_name}}
			</h4>
			<div class="row" ng-if='group_data.limits'>
				<div class="col-md-2">
					<i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "limits")'></i>
					Limits: <small>(edit enabled in advanced mode)</small>
				</div>
				<div class="col-md-6">
					<input ng-model='group_data.limits' type='text' class='form-control group-param' disabled />
				</div>
			</div>

			<div class='row' ng-if='group_data.rule'>
				<div class='col-md-2'>
					<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "rule")'></i></small>
					Rule: <small>(edit enabled in advanced mode)</small>
				</div>
				<div class="col-md-6">
					<input ng-model='group_data.rule' type='text' class='form-control group-param' disabled />
				</div>
			</div>

			<div class="row" ng-if='group_data.data !== undefined'>
				<div class="col-md-2">
					<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "data")'></i></small>
					Data:
				</div>
				<div class="col-md-6">
					<input ng-model='group_data.data' type='text' class='form-control group-param' />
				</div>
			</div>

			<div class="row" ng-if='group_data.call !== undefined'>
				<div class="col-md-2">
					<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "call")'></i></small>
					Call:
				</div>
				<div class="col-md-6">
					<input ng-model='group_data.call' type='text' class='form-control group-param' />
				</div>
			</div>

			<div class="row" ng-if='group_data.incoming_call !== undefined'>
				<div class="col-md-2">
					<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "incoming_call")'></i></small>
					Incoming Call:
				</div>
				<div class="col-md-6">
					<input ng-model='group_data.incoming_call' type='text' class='form-control group-param' />
				</div>
			</div>

			<div class="row" ng-if='group_data.incoming_sms !== undefined'>
				<div class="col-md-2">
					<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "incoming_sms")'></i></small>
					Incoming SMS:
				</div>
				<div class='col-md-6'>
					<input ng-model='group_data.incoming_sms' type='text' class='form-control group-param' />
				</div>
			</div>

			<div class="row" ng-if='group_data.sms !== undefined'>
				<div class="col-md-2">
					<small><i class='delete-plan glyphicon glyphicon-minus-sign' ng-click='deleteGroupParam(group_name, "sms")'></i></small>
					SMS:
				</div>
				<div class="col-md-6">
					<input ng-model='group_data.sms' type='text' class='form-control group-param' />
				</div>
			</div>
			
			<div class='row'>
				<div class='col-md-2'>
					<select class='plan-param-type form-control' ng-model='newGroupParam[group_name].type'>
						<option ng-repeat='param in groupParams' ng-disabled="entity.include.groups[group_name][param]">{{param}}</option>
					</select>
				</div>
				<div class='col-md-6'>
					<input type='text' class='form-control' ng-model='newGroupParam[group_name].value' ng-disabled='!newGroupParam[group_name].type' />
					<i class="add-plan-param glyphicon glyphicon-plus-sign" ng-click='addGroupParam(group_name)'></i>
				</div>
			</div>
		</div>
	</div>

	<div class="modal-footer">
		<?php if ($this->collectionName == 'plans' && $this->type == 'duplicate') : ?>
		<div class="edit_checkboxes">
		<input class="span1" id="duplicate_rates" name="duplicate_rates" type="checkbox" value="on" checked> <label class="span1" for="duplicate_rates">Duplicate rates</label>
		</div>
		<?php endif; ?>
		<button id="cancel" ng-click='cancel()' class="btn" aria-hidden="true">Close</button>
		<?php if (AdminController::authorized('write')) : ?>
		<button type='submit' class="btn btn-primary">Save changes</button>
		<?php endif; ?>
	</div>
	</form>
</div>