<div class="modal fade hide" id="confirmModal" tabindex="-2" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="confirmModalLabel"></h3>
	</div>
	<div class="modal-body">
	</div>
	<div class="modal-footer">
		<button id="cancelConfirm" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
		<button id="confirm" class="btn btn-primary">Remove</button>
	</div>
</div>

<div class="modal fade hide" id="popupModal" tabindex="-1" role="dialog" aria-labelledby="popupModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="popupLabel"></h3>
	</div>
	<div class="modal-body">

	</div>
	<div class="modal-footer">
		<button id="cancelPopup" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		<button id="save" class="btn btn-primary">Save changes</button>
	</div>
</div>

<div class="modal fade hide" id="LogPopup" tabindex="-3" role="dialog" aria-labelledby="LogPopupLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="LogPopupLabel"></h3>
	</div>
	<div class="modal-body">

	</div>
	<div class="modal-footer">
		<button id="cancelLogPopup" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	</div>
</div>