<style>
	.glyphicon-plus-sign {
		color: green;
		cursor: pointer;
	}

	.glyphicon-minus-sign {
		color: #bc2328;
		cursor: pointer;
	}
</style>

<?php
$protected = array();
	$entity = $this->data['entity']->getRawData();
	$availablePlans = $this->data['availablePlans'];
	foreach ($this->data['protectedKeys'] as $key) {
		if ($key !== '_id' && isset($entity[$key])) {
			$protected[$key] = $entity[$key];
			unset($entity[$key]);
		}
	}
	foreach ($this->data['hiddenKeys'] as $key) {
		unset($entity[$key]);
	}
?>

<script>
	var entity = <?php echo json_encode($this->data['entity']->getRawData()); ?>;
	var form_data = <?php echo json_encode($this->data); ?>;
	var available_plans = <?php echo json_encode($availablePlans); ?>;
</script>
<script src='<?php echo $this->baseUrl; ?>/js/controllers/RatesController.js'></script>
<div class="container component" ng-controller='RatesController' ng-init="init()">
	<center>
		<h2>{{entity.key}}</h2>
	</center>
<form class='form-inline' ng-submit='saveRate()'>
	<div id='rate-out-circuit-groups' ng-hide="entity.params.out_circuit_group === undefined">
		<h3>
			Out Circuit Group
		</h3>
		<div class='rate-out-circuit-group' ng-repeat="outCircuitGroup in entity.params.out_circuit_group">
			<label>From:</label>
			<input type='text' class='form-control' ng-model="outCircuitGroup.from" />
			<label>To:</label>
			<input type='text' class='form-control' ng-model="outCircuitGroup.to" />
			<i class='glyphicon glyphicon-minus-sign' ng-click="deleteOutCircuitGroup(outCircuitGroup)"></i>
		</div>
		<div>
			<label>From:</label>
			<input type='text' class='form-control' ng-model="newOutCircuitGroup.from" />
			<label>To:</label>
			<input type='text' class='form-control' ng-model="newOutCircuitGroup.to" />
			<i class='glyphicon glyphicon-plus-sign' ng-click="addOutCircuitGroup()"></i>
		</div>
	</div>

	<h3>
		Prefix
	</h3>
	<div id='rate-prefixes'>
		<div ng-repeat="prefix in entity.params.prefix track by $index">
			<input type="text" class="form-control" ng-model="entity.params.prefix[$index]" />
			<i class='glyphicon glyphicon-minus-sign' ng-click='deletePrefix($index)'></i>
		</div>
		<div>
			<input type="text" class="form-control" ng-model="newPrefix.value" />
			<i class='glyphicon glyphicon-plus-sign' ng-click="addPrefix()"></i>
		</div>
	</div>

	<div id='rate-record-types' ng-hide="entity.params.record_type === undefined">
		<h3>
			Record Types
		</h3>
		<div ng-repeat="recordType in entity.params.record_type track by $index">
			<input type="text" class="form-control" ng-model="recordType" />
			<i class='glyphicon glyphicon-minus-sign' ng-click='deleteRecordType($index)'></i>
		</div>
		<div>
			<input type="text" class="form-control" ng-model="newRecordType.value" />
			<i class='glyphicon glyphicon-plus-sign' ng-click="addRecordType()"></i>
		</div>
	</div>

	<hr/>

	<h2>Tariffs</h2>
	<div>
		<h3>Call</h3>
		<ul ng-repeat="(callRateName, callRate) in entity.rates.call">
			<h4>{{callRateName}}</h4>
			<div ng-repeat="callRateParams in callRate track by $index">
				<label for='rate-call-access'>Access</label>
				<input type='text' class='form-control' ng-model="callRate[$index].access" />
				<label for='rate-unit'>Unit</label>
				<select class='form-control' id='rate-call-unit' ng-model='callRate[$index].unit'>
					<option ng-repeat="unit in availableCallUnits" value="{{unit}}">{{unit}}</options>
				</select>
				<h4>
					Rates
				</h4>
				<div id='call-rates'>
					<table class='table table-striped table-bordered call-rates-table'>
						<thead>
							<tr>
								<th>Interval</th>
								<th>Price</th>
								<th>To</th>
								<th></th>
							</tr>
						</thead>
						<tbody id='call-rates-tbody'>
							<tr>
								<td><input type='text' ng-model="callRate[$index].rate.interval" class='form-control rate-call-interval' /></td>
								<td><input type='text' ng-model="callRate[$index].rate.price" class='form-control rate-call-price' /></td>
								<td><input type='text' ng-model="callRate[$index].rate.to" class='form-control rate-call-to' /></td>
								<td><i class='glyphicon glyphicon-minus-sign' ng-click="deleteCallRate(callRateName)"></i></td>
							</tr>
						</tbody>
					</table>

					<h4 ng-hide="true">Plans</h4>
					<div id='rate-call-plans' ng-hide="true">
						<div ng-repeat='callPlan in entity.rates.call.plans track by $index'>
							<select class='form-control rate-call-plan' ng-model='callPlan'>
								<option ng-repeat='availablePlan in availablePlans' value='{{availablePlan}}'>{{availablePlan}}</option>
							</select>
							<i class='glyphicon glyphicon-minus-sign' ng-click='deleteCallPlan($index)'></i>
						</div>
						<div>
							<select class='form-control' ng-model='newCallPlan.value'>
								<option ng-repeat='availablePlan in availablePlans' value='{{availablePlan}}'>{{availablePlan}}</option>
							</select>
							<i class='glyphicon glyphicon-plus-sign' ng-click='addCallPlan()'></i>
						</div>
					</div>
				</div>
			</div>
			<hr/>
		</ul>
		<ul>
			<div>
				<div class="row">
					<input ng-model="newCallRate.name" type="text" class="form-control" placeholder="Name" />
				</div>
				<label for='rate-call-access'>Access</label>
				<input type='text' class='form-control' ng-model="newCallRate.params.access" />
				<label for='rate-unit'>Unit</label>
				<select class='form-control' ng-model="newCallRate.params.unit">
					<option ng-repeat="unit in availableCallUnits" value="{{unit}}">{{unit}}</options>
				</select>
				<h4>
					Rates
				</h4>
				<div id='call-rates'>
					<table class='table table-striped table-bordered call-rates-table'>
						<thead>
							<tr>
								<th>Interval</th>
								<th>Price</th>
								<th>To</th>
								<th></th>
							</tr>
						</thead>
						<tbody id='call-rates-tbody'>
							<tr>
								<td><input type='text' ng-model="newCallRate.params.rate.interval" class='form-control rate-call-interval' /></td>
								<td><input type='text' ng-model="newCallRate.params.rate.price" class='form-control rate-call-price' /></td>
								<td><input type='text' ng-model="newCallRate.params.rate.to" class='form-control rate-call-to' /></td>
								<td><i class='glyphicon glyphicon-plus-sign' ng-click="addCallRate()"></i></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</ul>
	</div>

	<hr/>

	<div>
		<h3>SMS</h3>
		<ul ng-repeat="smsRate in entity.rates.sms">
			<label for='rate-sms-category'>Category</label>
			<input type='text' id='rate-sms-category' class='form-control' ng-model='smsRate.category' />
			<label for='rate-unit'>Unit: </label> <input type='text' disabled value='counter' />

			<h4>
				Rates
			</h4>
			<div id='sms-rates'>
				<table class='table table-striped table-bordered call-rates-table'>
					<thead>
						<tr>
							<th>Interval</th>
							<th>Price</th>
							<th>To</th>
							<th></th>
						</tr>
					</thead>
					<tbody id='sms-rates-tbody'>
						<tr ng-repeat="rate in smsRate.rate">
							<td><input type='number' ng-model="rate.interval" class='form-control rate-call-interval' /></td>
							<td><input type='text' ng-model="rate.price" class='form-control rate-call-price' /></td>
							<td><input type='text' ng-model="rate.to" class='form-control rate-call-to' /></td>
							<td><i class='glyphicon glyphicon-minus-sign' ng-click="deleteSMSRate(rate)"></i></td>
						</tr>
						<tr ng-hide="true">
							<td><input type="number" ng-model="newSMSRate.interval" class="form-control" /></td>
							<td><input type="text" ng-model='newSMSRate.price' class='form-control' /></td>
							<td><input type='text' ng-model='newSMSRate.to' class='form-control' /></td>
							<td><i class='glyphicon glyphicon-plus-sign' ng-click="addSMSRate()"></i></td>
						</tr>
					</tbody>
				</table>

				<h4>Plans</h4>
				<div id='rate-sms-plans'>
					<div ng-repeat='smsPlan in smsRate.plans track by $index'>
						<select class='form-control' ng-model='smsPlan'>
							<option ng-repeat='availablePlan in availablePlans' value='{{availablePlan}}'>{{availablePlan}}</option>
						</select>
						<i class='glyphicon glyphicon-minus-sign' ng-click='deleteSMSPlan($index)'></i>
					</div>
					<div>
						<select class='form-control' ng-model='newSMSPlan.value'>
							<option ng-repeat='availablePlan in availablePlans' value='{{availablePlan}}'>{{availablePlan}}</option>
						</select>
						<i class='glyphicon glyphicon-plus-sign' ng-click='addSMSPlan()'></i>
					</div>
				</div>
			</div>
		</ul>
	</div>
	<div class="modal-footer">
		<a href="#popupModal" data-type="update" data-toggle="modal" role="button"
			data-remote="<?php echo $this->baseUrl . '/admin/edit?coll=' . $this->data['collectionName'] . '&type=update&id=' . $entity['_id']; ?>">Advanced Mode</a>
		<?php if ($this->data['collectionName'] == 'plans' && $this->data['type'] == 'duplicate') : ?>
		<div class="edit_checkboxes">
		<input class="span1" id="duplicate_rates" name="duplicate_rates" type="checkbox" value="on" checked> <label class="span1" for="duplicate_rates">Duplicate rates</label>
		</div>
		<?php endif; ?>
		<button class="btn" aria-hidden="true">Cancel</button>
		<?php if (AdminController::authorized('write')) : ?>
		<button type='submit' class="btn btn-primary">Save changes</button>
		<?php endif; ?>
	</div>
</form>
</div>

<div class="modal fade" id="popupModal" tabindex="-1" role="dialog" aria-labelledby="popupModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 id="popupModalLabel"></h3>
			</div>
			<div class="modal-body">
			</div>
			<div class="modal-footer">
				<button id="cancelPopup" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
				<?php if (AdminController::authorized('write')) : ?>
					<button id="save" class="btn btn-primary">Save changes</button>
				<?php endif; ?>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div>
<script>
var opt = {
	change: function(data) {
		/* called on every change */
		_jsonData = data;
	},
	propertyclick: function(path) { /* called when a property is clicked with the JS path to that property */
		jsonPath = JSON.parse(path);
		var protectedKeys = <?php echo json_encode($this->protectedKeys); ?>;
		for (p in jsonPath) {
			if ($.inArray(jsonPath[p], protectedKeys) !== -1) {
				$('input[title="' + jsonPath[p] + '"]').attr('disabled', 'disabled');
			}
		}
	}
};
/* opt.propertyElement = '<textarea>'; */ // element of the property field, <input> is default
/* opt.valueElement = '<textarea>'; */  // element of the value field, <input> is default
//var _jsonEditor = $('#popupModal').jsonEditor(entity, opt);
$('#save').unbind();
$('#save').removeAttr("disabled");
$('#save').click(function saveClick() {
	$(this).attr('disabled', 'disabled');
	$(this).unbind("click", saveClick);
	console.log(_jsonData);
	var _ajaxOpts = {
		async: true,
		cache: false,
		//			dataType:'json',
		type: 'POST',
		data: {
			id: $('#form_id').html(),
			coll: $('#form_coll').html(),
			type: $('#form_type').html(),
			duplicate_rates: $('#duplicate_rates').is(':checked'),
			data: JSON.stringify(_jsonData)
		},
		success: function(data, textStatus, jqXHR) {
			if (data != 'null') {
				alert(data);
				$('#save').removeAttr("disabled");
				$('#save').bind("click", saveClick);
				return;
			}
			location.href = "<?php echo $this->baseUrl; ?>/admin/rates";
		},
		error: function(jqXHR, textStatus, errorThrown) {
			alert('some error occured');
		}
	};
	$.ajax('<?php echo $this->baseUrl; ?>/admin/save', _ajaxOpts);
});
</script>
