<style>
	.glyphicon-plus-sign {
		color: green;
		cursor: pointer;
	}
	
	.glyphicon-minus-sign {
		color: #bc2328;
		cursor: pointer;
	}
</style>

<?php
$protected = array();
	$entity = $this->data['entity']->getRawData();
	$availablePlans = $this->data['availablePlans'];
	foreach ($this->data['protectedKeys'] as $key) {
		if (isset($entity[$key])) {
			$protected[$key] = $entity[$key];
			unset($entity[$key]);
		}
	}
	foreach ($this->data['hiddenKeys'] as $key) {
		unset($entity[$key]);
	}
?>

<script>
	var entity = <?php echo json_encode($this->data['entity']->getRawData()); ?>;
	var form_data = <?php echo json_encode($this->data); ?>;
	var available_plans = <?php echo json_encode($availablePlans); ?>; 
</script>
<script src='<?php echo $this->baseUrl; ?>/js/controllers/RatesController.js'></script>
<div class="container component" ng-controller='RatesController'>	
	<center>
		<h2>{{entity.key}}</h2>
	</center>
<form class='form-inline' ng-submit='saveRate()'>
	<h3>
		Out Circuit Group
	</h3>
	<div id='rate-out-circuit-groups'>
		<div class='rate-out-circuit-group' ng-repeat="outCircuitGroup in entity.params.out_circuit_group">
			<label>From:</label>
			<input type='text' class='form-control' ng-model="outCircuitGroup.from" />
			<label>To:</label>
			<input type='text' class='form-control' ng-model="outCircuitGroup.to" />
			<i class='glyphicon glyphicon-minus-sign' ng-click="deleteOutCircuitGroup(outCircuitGroup)"></i>
		</div>
		<div>
			<label>From:</label>
			<input type='text' class='form-control' ng-model="newOutCircuitGroup.from" />
			<label>To:</label>
			<input type='text' class='form-control' ng-model="newOutCircuitGroup.to" />
			<i class='glyphicon glyphicon-plus-sign' ng-click="addOutCircuitGroup()"></i>
		</div>
	</div>

	<h3>
		Prefix
	</h3>
	<div id='rate-prefixes'>
		<div ng-repeat="prefix in entity.params.prefix track by $index">
			<input type="text" class="form-control" ng-model="prefix" />
			<i class='glyphicon glyphicon-minus-sign' ng-click='deletePrefix($index)'></i>
		</div>
		<div>
			<input type="text" class="form-control" ng-model="newPrefix.value" />
			<i class='glyphicon glyphicon-plus-sign' ng-click="addPrefix()"></i>
		</div>
	</div>
	
	<h3>
		Record Types
	</h3>
	<div id='rate-record-types'>
		<div ng-repeat="recordType in entity.params.record_type track by $index">
			<input type="text" class="form-control" ng-model="recordType" />
			<i class='glyphicon glyphicon-minus-sign' ng-click='deleteRecordType($index)'></i>
		</div>
		<div>
			<input type="text" class="form-control" ng-model="newRecordType.value" />
			<i class='glyphicon glyphicon-plus-sign' ng-click="addRecordType()"></i>
		</div>
	</div>

	<hr/>

	<h2>Tariffs</h2>
	<h3>Call</h3>
	<div>
		<ul>
		<label for='rate-call-access'>Access</label>
		<input type='number' class='form-control' ng-model="entity.rates.call.access" />
		<label for='rate-unit'>Unit</label>
		<select class='form-control' id='rate-call-unit'>
			<option ng-repeat="unit in availableCallUnits" value="{{unit}}">{{unit}}</options>
		</select>	
		<h4>
			Rates
		</h4>
		<div id='call-rates'>
			<table class='table table-striped table-bordered call-rates-table'>
				<thead>
					<tr>
						<th>Interval</th>
						<th>Price</th>
						<th>To</th>
						<th></th>
					</tr>
				</thead>
				<tbody id='call-rates-tbody'>
					<tr ng-repeat="rate in entity.rates.call.rate">
						<td><input type='number' ng-model="rate.interval" class='form-control rate-call-interval' /></td>
						<td><input type='text' ng-model="rate.price" class='form-control rate-call-price' /></td>
						<td><input type='text' ng-model="rate.to" class='form-control rate-call-to' /></td>	
						<td><i class='glyphicon glyphicon-minus-sign' ng-click="deleteCallRate(rate)"></i></td>
					</tr>
					<tr>
						<td><input type="number" ng-model="newCallRate.interval" class="form-control" /></td>
						<td><input type="text" ng-model='newCallRate.price' class='form-control' /></td>
						<td><input type='text' ng-model='newCallRate.to' class='form-control' /></td>
						<td><i class='glyphicon glyphicon-plus-sign' ng-click="addCallRate()"></i></td>
					</tr>
				</tbody>
			</table>
			
			<h4>Plans</h4>
			<div id='rate-call-plans'>
				<div ng-repeat='callPlan in entity.rates.call.plans track by $index'>
					<select class='form-control rate-call-plan' ng-model='callPlan'>
						<option ng-repeat='availablePlan in availablePlans' value='{{availablePlan}}'>{{availablePlan}}</option>
					</select>
					<i class='glyphicon glyphicon-minus-sign' ng-click='deleteCallPlan($index)'></i>
				</div>
				<div>
					<select class='form-control' ng-model='newCallPlan.value'>
						<option ng-repeat='availablePlan in availablePlans' value='{{availablePlan}}'>{{availablePlan}}</option>
					</select>
					<i class='glyphicon glyphicon-plus-sign' ng-click='addCallPlan()'></i>
				</div>
			</div>
		</div>
		</ul>
	</div>
	
	<hr/>

	<h3>SMS</h3>
	<div>
		<ul>
		<label for='rate-sms-category'>Category</label>
		<input type='text' id='rate-sms-category' class='form-control' ng-model='entity.rates.sms.category' />
		<label for='rate-unit'>Unit: </label> <input type='text' disabled value='counter' />

		<h4>
			Rates
		</h4>
		<div id='sms-rates'>
			<table class='table table-striped table-bordered call-rates-table'>
				<thead>
					<tr>
						<th>Interval</th>
						<th>Price</th>
						<th>To</th>
						<th></th>
					</tr>
				</thead>
				<tbody id='sms-rates-tbody'>
					<tr ng-repeat="rate in entity.rates.sms.rate">
						<td><input type='number' ng-model="rate.interval" class='form-control rate-call-interval' /></td>
						<td><input type='text' ng-model="rate.price" class='form-control rate-call-price' /></td>
						<td><input type='text' ng-model="rate.to" class='form-control rate-call-to' /></td>	
						<td><i class='glyphicon glyphicon-minus-sign' ng-click="deleteSMSRate(rate)"></i></td>
					</tr>
					<tr>
						<td><input type="number" ng-model="newSMSRate.interval" class="form-control" /></td>
						<td><input type="text" ng-model='newSMSRate.price' class='form-control' /></td>
						<td><input type='text' ng-model='newSMSRate.to' class='form-control' /></td>
						<td><i class='glyphicon glyphicon-plus-sign' ng-click="addSMSRate()"></i></td>
					</tr>
				</tbody>
			</table>
			
			<h4>Plans</h4>
			<div id='rate-sms-plans'>
				<div ng-repeat='smsPlan in entity.rates.sms.plans track by $index'>
					<select class='form-control' ng-model='smsPlan'>
						<option ng-repeat='availablePlan in availablePlans' value='{{availablePlan}}'>{{availablePlan}}</option>
					</select>
					<i class='glyphicon glyphicon-minus-sign' ng-click='deleteSMSPlan($index)'></i>
				</div>
				<div>
					<select class='form-control' ng-model='newSMSPlan.value'>
						<option ng-repeat='availablePlan in availablePlans' value='{{availablePlan}}'>{{availablePlan}}</option>
					</select>
					<i class='glyphicon glyphicon-plus-sign' ng-click='addSMSPlan()'></i>
				</div>
			</div>
		</div>
		</ul>
	</div>
	<div class="modal-footer">
		<?php if ($this->data['collectionName'] == 'plans' && $this->data['type'] == 'duplicate') : ?>
		<div class="edit_checkboxes">
		<input class="span1" id="duplicate_rates" name="duplicate_rates" type="checkbox" value="on" checked> <label class="span1" for="duplicate_rates">Duplicate rates</label>
		</div>
		<?php endif; ?>
		<button class="btn" aria-hidden="true">Cancel</button>
		<?php if (AdminController::authorized('write')) : ?>
		<button type='submit' class="btn btn-primary">Save changes</button>
		<?php endif; ?>
	</div>
</form>
</div>