
<html>
	<head>
		<h1>Fraud ftp status</h1>
	</head>
	<body>
		<p><?php print($this->testConnection ? "ftp connection tested successfully" : " ftp connection test failed"); ?></p>
		<p>Last file received: <?php print($this->file_name) ?> time: <?php print($this->received_time) ?><p/>
		<div>
			Files to be received soon:
			<?php
			$i=1;
			foreach($this->files_list as $file) :
				if ($file->isDirectory()) continue;
				print "<div>" . $i++ . '. '. $file->name . " size: " . $file->size(). "</div>";
			endforeach;
			?>
		</div>
	</body>
</html>