<script type="text/javascript">
	var coll = <?php echo json_encode(strtolower($this->title)); ?>;
</script>
<div class="container component">
	<h1><?php echo $this->title; ?></h1>
	<?php
//	if (isset($criteria_tpl)) {
//		$this->display($criteria_tpl . '.phtml', array());
//	}
	$this->display('toolbar.phtml', array());
	print '<div style="clear:both;"></div>';
	if (isset($this->data) && $this->data instanceof Mongodloid_Cursor) :
		print '<section id="no-more-tables"><table id="data_table" class="table table-striped table-bordered table-no-more-tables">';
		print '<thead><tr><th>#</th>';
		foreach ($this->columns as $value) {
			print '<th>' . $value . '</th>';
		}
		print '</tr></thead><tbody>';

		$c = $this->offset;
		foreach ($this->data as $item) {
//			$shani = $this->data->count();
			print '<tr>';
			print '<td data-title=\'#\'><label class="checkbox"><a onclick="update_current(this);" href="#popupModal" data-type="update" data-toggle="modal" role="button" data-remote="">#' . ($c + 1) . '</a>&nbsp;<input value="' . $item['_id'] . '" type="checkbox" id="chk' . $c++ . '"/></label></td>';
			foreach ($this->columns as $h => $columnName) {
				$data = $item->get($h);
				print '<td data-title=' . $columnName . '>';
				if (isset($edit_key) && $h == $edit_key) {
					$url = $this->baseUrl . '/admin/edit?type=' . strtolower($this->title) . '&id=' . $item['_id'];
					print '<a href="#popupModal " data-remote="' . $url . '" role="button" data-toggle="modal">' . $data . '</a>';
				} else if (($h == 'from' || $h == 'to' || $h == 'urt' || $h == 'notify_time') && $data) {
					$dateFormat = "Y-m-d H:i:s";
					if (!empty($item["tzoffset"])) {
						// TODO change this to regex
						$timsetamp = $item['urt']->sec;
						$tzoffset = $item['tzoffset'];
						$sign = substr($tzoffset, 0, 1);
						$hours = substr($tzoffset, 1, 2);
						$minutes = substr($tzoffset, 3, 2);
						$time = $hours . ' hours ' . $minutes . ' minutes';
						if ($sign == "-") {
							$time .= ' ago';
						}
						$timsetamp = strtotime($time, $timsetamp);
						$zend_date = new Zend_Date($timsetamp);
						$zend_date->setTimezone('UTC');
						echo $zend_date->toString($dateFormat, 'php') . $item['tzoffset'];
					} else {
						$zend_date = new Zend_Date($data->sec);
						echo $zend_date->toString($dateFormat, 'php');
					}
				} else {
					print $data;
				}
				print '</td>';
			}
			print '</tr>';
		}
		print '</tbody></table></section>';

		// print pagination
		echo $this->pagination;
		echo $this->sizeList;
	else :
		print "No data";
	endif;
	?>

    <div class="modal fade hide" id="confirmModal" tabindex="-2" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 id="confirmModalLabel"></h3>
		</div>
		<div class="modal-body">
		</div>
		<div class="modal-footer">
			<button id="cancelConfirm" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
			<button id="confirm" class="btn btn-primary">Remove</button>
		</div>
    </div>

    <div class="modal fade hide" id="popupModal" tabindex="-1" role="dialog" aria-labelledby="popupModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 id="popupLabel"></h3>
		</div>
		<div class="modal-body">

		</div>
		<div class="modal-footer">
			<button id="cancelPopup" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<button id="save" class="btn btn-primary">Save changes</button>
		</div>
    </div>

    <div class="modal fade hide" id="LogPopup" tabindex="-3" role="dialog" aria-labelledby="LogPopupLabel" aria-hidden="true">
        <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h3 id="LogPopupLabel"></h3>
        </div>
        <div class="modal-body">

        </div>
        <div class="modal-footer">
			<button id="cancelLogPopup" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>
    </div>

</div>