<?php

$c = $this->offset;
foreach ($this->data as $item) {
	if (strtolower($this->title) == 'log' && isset($item['start_process_time']) && !isset($item['process_time'])) :
		print '<tr class="progress' . ((time() - $item['start_process_time']->sec) > 3600 ? ' alert-danger':'') . '">';
	else:
		print '<tr>';
	endif;
	print '<td data-title=\'#\'>'
		. '<label class="checkbox">'
		. '<a onclick="update_current(this);" href="#popupModal" data-type="update" data-toggle="modal" role="button" data-remote="">#' . ($c + 1) . '</a>&nbsp;'
		. '<input value="' . $item['_id'] . '" type="' . (AdminController::authorized('write') ? 'checkbox' : 'hidden') . '" id="chk' . $c . '"/>'
		. '</label></td>';
	$c++;
	foreach ($this->columns as $h => $columnName) {
		$data = $item->get($h);
		print '<td data-title=' . $columnName . '>';
		if (isset($edit_key) && $h == $edit_key) {
			$url = $this->baseUrl . '/admin/edit?type=' . strtolower($this->title) . '&id=' . $item['_id'];
			print '<a href="#popupModal " data-remote="' . $url . '" role="button" data-toggle="modal">' . $data . '</a>';
		} else if (($h == 'from' || $h == 'to' || $h == 'urt' || $h == 'notify_time') && $data) {
			$dateFormat = "Y-m-d H:i:s";
			if (!empty($item["tzoffset"])) {
				// TODO change this to regex and move to method in model
				$tzoffset = $item['tzoffset'];
				$sign = substr($tzoffset, 0, 1);
				$hours = substr($tzoffset, 1, 2);
				$minutes = substr($tzoffset, 3, 2);
				$time = $hours . ' hours ' . $minutes . ' minutes';
				if ($sign == "-") {
					$time .= ' ago';
				}
				$zend_date = new Zend_Date(strtotime($time, $item['urt']->sec));
				$zend_date->setTimezone('UTC');
				echo $zend_date->toString($dateFormat, 'php') . $item['tzoffset'];
			} else {
				$zend_date = new Zend_Date($data->sec);
				echo $zend_date->toString($dateFormat, 'php');
			}
		} else if ($h == 'arate' && isset ($item['arate_id'])) {
			$url = $this->baseUrl . '/admin/edit?coll=rates&type=update&id=' . $item['arate_id'];
			print '<a href="#popupModal " data-remote="' . $url . '" role="button" data-toggle="modal" title="' . $data . '">' . $data . '</a>';
		} else {
			print $data;
		}
		print '</td>';
	}
	print '</tr>';
}