<?php
in_array($active, array('lines', 'subscribers', 'subscribers_auto_renew_services', 'balances')) ? $showSidePanel = ' show-side-panel ' : $showSidePanel = '';
if ($active == 'lines') {
	print '<section id="no-more-tables"><table id="data_table" 
				   data-toggle="table" 
				   data-detail-formatter="detailFormatter" 
				   class="table table-striped table-bordered table-no-more-tables show-side-panel">';
} else {
	print '<section id="no-more-tables"><table id="data_table" class="table table-striped table-bordered table-no-more-tables' . $showSidePanel . '">';	
}
print '<thead><tr><th>'
. '<label class="checkbox">#'
	. '<input type="checkbox" id="check_all" />'
	. '</label></th>';
foreach ($this->columns as $value) {
	print '<th>' . $value . '</th>';
}
print '</tr></thead><tbody>';