<div class="toolbar-buttons">
	<span><input type="hidden" name="new_search" value="1"><button type="submit" class="btn btn-success"><i class="icon-search"> </i>Submit</button></span>
	<script type="text/javascript">
		var active_collection = '<?php echo $active; ?>';
	</script>
	<?php if (!in_array($active, array('events', 'log'))) : ?>
		<span class="pull-right">
		<?php endif; ?>
		<?php if (in_array($active, array('rates', 'plans', 'users', 'tadigs')) && AdminController::authorized('write')) : ?>
			<?php if (!in_array($active, array('users', 'tadigs'))) : ?>
				<span><a id='close_and_new' data-type="close_and_new" href="#popupModal" class="btn btn-primary" data-toggle="modal" role="button">Close & new</a></span>
			<?php endif; ?>
			<?php if (in_array($active, array('users', 'tadigs'))) : ?>
				<span><a id='new' data-type="new" href="#popupModal" class="btn btn-warning" data-toggle="modal" role="button">New</a></span>
			<?php endif; ?>
			<span><a id='duplicate' data-type="duplicate" href="#popupModal" class="btn btn-info" data-toggle="modal" role="button">Duplicate</a></span>
		<?php endif; ?>
		<?php if (!in_array($active, array('events', 'log', 'balances')) && AdminController::authorized('write')) : ?>
			<span><a id='remove' data-type="remove" href="#confirmModal" class="btn btn-danger" data-toggle="modal" role="button"><i class="icon-remove"> </i>Remove</a></span>
		<?php endif; ?>
		<?php if ($active == 'lines' || $active == 'balances') : ?>
			<span><a id='download' data-type="download" href="/admin/csvExport?collection=<?php echo $active; ?>" class="btn export-button"><i class="icon-download-alt"> </i>Export to CSV</a></span>
			<?php if ($active == 'lines' && AdminController::authorized('write')) : ?>
				<span><a id='upload' data-type="upload" href="#uploadModal" class="btn btn-primary" data-toggle="modal" role="button"><i class="icon-upload"> </i>Import</a></span>
			<?php endif; ?>
		<?php endif; ?>
		<?php if ($active == 'rates') : ?>
			<?php if (AdminController::authorized('write')) : ?>
				<span><a id='import_prices' data-type="upload" href="#importPricesModal" class="btn btn-primary" data-toggle="modal" role="button"><i class="icon-upload"> </i>Import</a></span>
			<?php endif; ?>
			<span><a id='export_prices' data-type="download" href="javascript:exportRates();" class="btn export-button"><i class="icon-download"> </i>Export to CSV</a></span>
		<?php endif; ?>
	</span>
</div>
