<div class="toolbar">
	<form action="" method="post" class="form-vertical">
		<?php if (strtolower($this->title) == 'lines') : ?>

			<?php
		endif;
		if (is_array($this->filter_fields_order) && is_array($this->filter_fields)) {
			foreach ($this->filter_fields_order as $row_fields) {
				echo	"<div class=\"control-group\">
							<div class=\"controls form-inline\">";
				foreach ($row_fields as $filter_field_key => $field_view) {
					$filter_field = $this->filter_fields[$filter_field_key];
					if ($filter_field['input_type'] == 'boolean') {
						echo "&nbsp;<label class=\"checkbox\">
							<input class=\"span" . $field_view['width'] . "\" name=\"" . $filter_field['key'] . "\" type=\"checkbox\">" . $filter_field['display'] .
						"</label>";
					} else if ($filter_field['input_type'] == 'number') {
						echo	"&nbsp;<label class=\"control-label\" for=\"" . $filter_field['key'] . "\">" . $filter_field['display'] . "</label>
								<input id=\"" . $filter_field['key'] . "\" class=\"span" . $field_view['width'] . "\" name=\"" . $filter_field['key'] . "\" type=\"text\" value=\"" . $filter_field['default'] . "\">";
					} else if ($filter_field['input_type'] == 'date') {
						echo	"&nbsp;&nbsp;<label class=\"control-label\">" . $filter_field['display'] . "</label>
								<div class=\"input-append date\" id=\"datetimepicker\" data-date=\"" . $filter_field['default'] . "\" data-date-format=\"yyyy-MM-dd hh:mm:ss\">
								<input name=\"" . $filter_field['key'] . "\" class=\"controls-row span" . $field_view['width'] . "\" size=\"16\" type=\"text\" value=\"" . $filter_field['default'] . "\">
								<span class=\"add-on\"><i class=\"icon-th\"></i></span>
								</div>";
					}
				}
				echo "</div></div>";
			}
		}
		if (!in_array(strtolower($this->title), array('events', 'log'))) :
			?>
			<span><button type="submit" class="btn">Submit</button></span>
			<script type="text/javascript">
				var edit_url_prefix = <?php echo json_encode($this->baseUrl . '/admin/edit?coll=' . strtolower($this->title) . '&id='); ?>;
				var confirm_url_prefix = <?php echo json_encode($this->baseUrl . '/admin/confirm?coll=' . strtolower($this->title) . '&id='); ?>;
			</script>
			<span class="pull-right">
			<span><a id='update_current' data-type="update" href="#popupModal" class="btn btn-warning" data-toggle="modal" role="button" data-remote="">Update current</a></span>
		<?php endif; ?>
		<?php if (strtolower($this->title) == 'rates' || strtolower($this->title) == 'plans') : ?>
			<span><a id='close_and_new' data-type="close_and_new" href="#popupModal" class="btn btn-primary" data-toggle="modal" role="button" data-remote="">Close & new</a></span>
			<span><a id='duplicate' data-type="duplicate" href="#popupModal" class="btn btn-info" data-toggle="modal" role="button" data-remote="">Duplicate</a></span>
		<?php endif; ?>
		<?php if (!in_array(strtolower($this->title), array('events', 'log'))) : ?>
			<span><a id='remove' data-type="remove" href="#confirmModal" class="btn btn-danger" data-toggle="modal" role="button" data-remote=""><i class="icon-remove"> </i>Remove</a></span>
			</span>
		<?php endif; ?>

	</form>
</div>