<?php
// todo: remove this
require_once '../application/helpers/Admin/Lines.php';
//print_R($this->session->order);die;
?>
<div class="toolbar toolbar-<?php echo strtolower($this->title); ?>">
	<form id="search-criteria" action="" method="POST" class="form-vertical">
		<?php
//		print_R($this->filter_fields_order);
//		print_R($this->filter_fields);die;
		if (is_array($this->filter_fields_order) && is_array($this->filter_fields)) {
			foreach ($this->filter_fields_order as $key => $row_fields) {
				echo "<div class=\"control-group control-group" . $key . "\">
							<div class=\"controls form-inline\">";
				foreach ($row_fields as $filter_field_key => $field_view) {
					$filter_field = $this->filter_fields[$filter_field_key];
					if ($filter_field['input_type'] == 'boolean') {
						echo "<input class=\"span" . $field_view['width'] . "\" id=\"" . $filter_field['key'] . "\" name=\"" . $filter_field['key'] . "\" type=\"checkbox\"" . (isset($this->session->$filter_field['key']) && $this->session->$filter_field['key'] == "on" ? " value=\"1\" checked=\"checked\"" : "") . ">" 
							. "<label class=\"checkbox\" for=\"" . $filter_field['key'] . "\">" . $filter_field['display'] . "</label>";
					} else if ($filter_field['input_type'] == 'number') {
						echo "&nbsp;<label class=\"control-label\" for=\"" . $filter_field['key'] . "\">" . $filter_field['display'] . "</label>
								<input id=\"" . $filter_field['key'] . "\" class=\"span" . $field_view['width'] . "\" name=\"" . $filter_field['key'] . "\" type=\"text\" value=\"" . (isset($this->session->$filter_field['key']) ? $this->session->$filter_field['key'] : $filter_field['default']) . "\">";
					} else if ($filter_field['input_type'] == 'text') {
						echo "&nbsp;<label class=\"control-label\" for=\"" . $filter_field['key'] . "\">" . $filter_field['display'] . "</label>
								<input id=\"" . $filter_field['key'] . "\" class=\"span" . $field_view['width'] . "\" name=\"" . $filter_field['key'] 
								. "\" type=\"text\" value=\"" 
									. (isset($this->session->$filter_field['key']) ? $this->session->$filter_field['key'] : $filter_field['default']) 
							. "\">";
					} else if ($filter_field['input_type'] == 'date') {
						echo "&nbsp;<label class=\"control-label\">" . $filter_field['display'] . "</label>
								<div class=\"input-append date\" id=\"datetimepicker_" . $filter_field['key'] . "\" data-date=\"" . $filter_field['default'] . "\" data-date-format=\"yyyy-MM-dd hh:mm:ss\">
								<input name=\"" . $filter_field['key'] . "\" class=\"controls-row span" . $field_view['width'] . "\" size=\"16\" type=\"text\" value=\"" . (isset($this->session->$filter_field['key']) ? $this->session->$filter_field['key'] : $filter_field['default']) . "\">
								<span class=\"add-on\"><i class=\"icon-th\"></i></span>
								</div>";
					} else if ($filter_field['input_type'] == 'multiselect') {
						echo "&nbsp;<label class=\"control-label\">" . $filter_field['display'] . "</label>
						<select id=\"" . $filter_field['key'] . "\" name=\"" . $filter_field['key'] . "[]\" class=\"multiselect\" multiple=\"multiple\">";
						foreach ($filter_field['values'] as $value => $name) {
							if (is_array($this->session->$filter_field['key'])) {
								if (in_array($value, $this->session->$filter_field['key'])) {
									$selected = " selected";
								} else {
									$selected = "";
								}
							} else if (is_array($filter_field['default']) && in_array($value, $filter_field['default'])) {
								$selected = " selected";
							} else {
								$selected = "";
							}
							echo "<option value=\"" . $value . "\"" . $selected . ">" . $name . "</option>";
						}
						echo "</select>";
					}
				}
				echo "</div></div>";
			}

			if (strtolower($this->title) == 'lines') :
				echo "<div><a href=\"javascript:void(0)\" class=\"advanced-options\" href=\"#\">Advanced options <i class=\"" . (Lines::isManualFilter($this->session) ? "icon-chevron-up" : "icon-chevron-down") . "\"></i></a></div>
                            <div id = \"manual_filters\"" . (Lines::isManualFilter($this->session) ? "" : " style=\"display:none;\"") . ">";
				if (Lines::isManualFilter($this->session)) {
					for ($i = 0; $i < count($this->session->manual_key); $i++) {
						echo Lines::getFilterRow($this->session->manual_key[$i], $this->session->manual_type[$i], $this->session->manual_operator[$i], $this->session->manual_value[$i]);
					}
				} else {
					echo Lines::getFilterRow(); // add first manual filter on load
				}
				echo "</div>";
			elseif (strtolower($this->title) == 'rates') :
			endif;

			if (is_array($this->sort_fields)) {
				echo "Sort by: <div class=\"control-group\">
		<div class=\"controls form-inline\">
			 <select id=\"sort_by\" name=\"sort_by\">";
				foreach ($this->sort_fields as $sort_field_key => $sort_field_display) {
					echo "<option value=\"" . $sort_field_key . "\"" . (isset($this->session->sort_by) && $this->session->sort_by == $sort_field_key ? " selected=\"selected\"" : "") . ">" . $sort_field_display . "</option>";
				}
				echo "</select>
			<label class=\"radio inline\">
                                <input name=\"order\" value=\"desc\" type=\"radio\"" . ((isset($this->session->order) && $this->session->order == "desc") ? " checked=\"checked\"" : "") . "> Descending order
			</label>
			<label class=\"radio inline\">
                                <input name=\"order\" value=\"asc\" type=\"radio\"" . ((isset($this->session->order) && $this->session->order == "desc") ? "" : " checked=\"checked\"") . "> Ascending order
			</label>
		</div></div>";
			}
		}
		?>

		<span><input type="hidden" name="new_search" value="1"><button type="submit" class="btn btn-success"><i class="icon-search"> </i>Submit</button></span>
		<?php if (!in_array(strtolower($this->title), array('events', 'log'))) : ?>
			<script type="text/javascript">
				var edit_url_prefix = <?php echo json_encode($this->baseUrl . '/admin/edit?coll=' . strtolower($this->title) . '&id='); ?>;
				var confirm_url_prefix = <?php echo json_encode($this->baseUrl . '/admin/confirm?coll=' . strtolower($this->title) . '&id='); ?>;
			</script>
			<span class="pull-right">
			<?php endif; ?>
			<?php if (strtolower($this->title) == 'rates' || strtolower($this->title) == 'plans') : ?>
				<span><a id='close_and_new' data-type="close_and_new" href="#popupModal" class="btn btn-primary" data-toggle="modal" role="button" data-remote="">Close & new</a></span>
				<span><a id='duplicate' data-type="duplicate" href="#popupModal" class="btn btn-info" data-toggle="modal" role="button" data-remote="">Duplicate</a></span>
			<?php endif; ?>
			<?php if (!in_array(strtolower($this->title), array('events', 'log'))) : ?>
				<span><a id='remove' data-type="remove" href="#confirmModal" class="btn btn-danger" data-toggle="modal" role="button" data-remote=""><i class="icon-remove"> </i>Remove</a></span>
			<?php endif; ?>
			<?php if (strtolower($this->title) == 'lines') : ?>
				<span><a id='download' data-type="download" href="/admin/csvExport" class="btn btn-info"><i class="icon-download-alt"> </i>Export to CSV</a></span>
			<?php endif; ?>
		</span>

	</form>
</div>