<div class="toolbar toolbar-<?php echo strtolower($this->title); ?>">
	<form id="search-criteria" action="" method="POST" class="form-vertical">
		<?php
		if (isset($this->group_fields) && is_array($this->group_fields)) {
			echo '<div class="control-group control-group0">';
			foreach ($this->group_fields as $group_field) {
				$default_key = isset($this->session->$group_field['key']) ? $this->session->$group_field['key'] : $group_field['default'];
				$this->group_value = $group_field['values'][$default_key];
				echo '<div class="controls form-inline">&nbsp;<label class="control-label">' . $group_field['display'] . '</label>
						<select id="' . $group_field['key'] . '" name="' . $group_field['key'] . '" class="form-control">';
				foreach ($group_field['values'] as $key => $value) {
					echo '<option value="' . $key . '"' . ($default_key == $key ? ' selected' : '') . '>' . $value . '</option>';
				}
				echo '</select></div>';
			}
			echo '</div>';
		}
		echo "<div class=\"control-group control-group1\">
					<div class=\"controls form-inline\">";
		foreach ($this->filter_fields as $filter_field) {
			if ($filter_field['input_type'] == 'date') {
				echo '&nbsp;<label class="control-label">' . $filter_field['display'] . '</label>
 								<div class="input-append date wholesale-date" id="datetimepicker_' . $filter_field['key'] . '" data-date="' . (isset($this->session->$filter_field['key']) ? $this->session->$filter_field['key'] : $filter_field['default']) . '" data-date-format="YYYY-MM-DD">
								<input name="' . $filter_field['key'] . '" class="form-control" size="16" type="text" value="' . (isset($this->session->$filter_field['key']) ? $this->session->$filter_field['key'] : $filter_field['default']) . '">
								<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
								</div>';
			}
		}
		echo '</div></div>';
		?>

		<div class="toolbar-buttons">
			<span><input type="hidden" name="new_search" value="1"><button type="submit" class="btn btn-success"><i class="icon-search"> </i>Submit</button></span>
		</div>
	</form>
</div>