<?php

$report_params = current($tbl_params);
echo '<div class="wholesale-popup">
<h2>' . $report_params['title'] . ' (' . ($this->carrier ? $this->carrier : $this->from_day) . ')' . '</h2>';

$graph = Admin_Graphs::prepareGraph($this->data['table_data'], $this->group_by_display, $this->group_by, $report_params['fields'], array('graph_id' => (strtolower($report_params['direction']) . '_graph'), 'graph_class' => 'wholesale-graph'));
echo Admin_Graphs::printGraph($graph, false, 1);

foreach (array_keys($tbl_params) as $index => $report_type) {
	$report_params = $tbl_params[$report_type];
	$column_counter = 0;
	foreach ($report_params['fields'] as $usage_type => $usage_fields) {
		foreach ($usage_fields as $field) {
			$table_totals[$column_counter] = 0;
			$column_counter++;
		}
	}
	echo '<div class="tab-pane' . (isset($report_params['default']) && $report_params['default'] ? ' active' : '') . '" id="tabs-' . ($index + 1) . '">
		<table border="1" data-type="' . $report_params['direction'] . '" class="wholesale-table">';

	echo "<tr>";
	echo '<th rowspan="2">' . $this->group_by_display . '</th>';
	foreach ($report_params['fields'] as $usage_type => $fields) {
		echo '<th colspan="' . count($fields) . '">' . $usage_type . '</th>';
	}
	echo "</tr>";
	echo "<tr>";
	foreach ($report_params['fields'] as $fields) {
		foreach ($fields as $field) {
			echo '<th>' . $field['display'] . "</th>";
		}
	}
	echo "</tr>";

	foreach ($this->data['available_group_values'] as $group_value) {
		echo '<tr><td>' . $group_value . '</td>';
		$column_counter = 0;
		foreach ($report_params['fields'] as $usage_type => $usage_fields) {
			foreach ($usage_fields as $field) {
				echo '<td>';
				if (isset($this->data['table_data'][$usage_type][$group_value][$field['display']])) {
					if ($field['value'] == 'cost') {
						echo number_format($this->data['table_data'][$usage_type][$group_value][$field['display']], 2);
					} else {
						echo $this->data['table_data'][$usage_type][$group_value][$field['display']];
					}
					$table_totals[$column_counter]+=$this->data['table_data'][$usage_type][$group_value][$field['value']];
				} else {
					echo '&nbsp;';
				}
				echo '</td>';
				$column_counter++;
			}
		}
		echo '</tr>';
	}
	echo '<tr class="totals">';
	echo '<td>Total</td>';
	for ($i = 0; $i < $column_counter; $i++) {
		echo '<td>' . number_format($table_totals[$i],2) . '</td>';
	}
	echo '</tr>';
	echo '</table>';
	echo '</div>';
}