<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="<?php echo $this->css_path ?>" />
		<script>
				function footerAdjust() {
					var vars = {};
					var x = window.location.search.substring(1).split('&');
					for (var i in x) {
						var z = x[i].split('=', 2);
						vars[z[0]] = unescape(z[1]);
					}
					var x = ['frompage', 'topage', 'page', 'webpage', 'subsection', 'subsubsection'];
					for (var i in x) {
						var y = document.getElementsByClassName(x[i]);
						for (var j = 0; j < y.length; ++j)
							if (x[i] == 'page' || x[i] == 'topage') {
								var t = parseInt(vars[x[i]]) + 1;
								y[j].textContent = t;
							} else {
								y[j].textContent = vars[x[i]];
							}
					}


					toggleFooters(vars['page'],vars['topage']);
				}

				function toggleFooters(pageNum, totalPages) {
					if(pageNum == 1) {
						document.getElementById('first-footer').style.display = "block";
						document.getElementById('regular-footer').style.display = "none";
					}
//					if(pageNum == totalPages) {
//						document.getElementById('regular-footer').style.display = "none";
//					}
				}
						
		</script>
	</head>

	<body onload="footerAdjust();" style="height:250px;background:transparent;">
		<div class="page-margins">
			<footer class="main"  id="regular-footer" style="height:160px;">
				<div class="shell">
					<section class="section">
						<div class="message" style="">
							<p>שים לב, יתכנו פערים בין הסכום לחיוב לבין סכימת החיובים בסיכום הביניים, מאחר והסכום לחיוב מחושב ברמת דיוק גבוהה יותר.</p>
						</div><!-- /.message -->
					</section><!-- /.section -->
				</div><!-- /.shell -->
			</footer><!-- /.main -->
			<footer id="first-footer" style="display:none;margin-top:-2px;margin-bottom: 2px">
				<div class="table table--orange" >
					<table>
						<tfoot>
							<tr>
								<td style="padding-top:0;padding-bottom: 0">
									<p>&rlm;בנושא סלולר ותפעול מכשירים חייגו <span>0051*</span> מה<span> - we4G</span> או <span>1-801-515151</span>&rlm; חינם מכל טלפון, בימים א‘-ה‘ בשעות <span>08:00 - 18:00</span>&rlm; וביום ו‘ וערבי חג בין השעות <span>08:00 - 13:00</span>.&rlm; פקס שירות לקוחות: <span>03-3094091.</span>&rlm; בקשות בנושא הפסקת שירות / ניתוק שירות / סיום התקשרות ניתן לשלוח ל-  <span>nitook@we4g.co.il</span>&rlm; או פקס <span>03-3094094</span>.&rlm; להגשת תלונה לנציב התלונות ניתן לשלוח ל- <span>pniot@we4g.co.il</span>&rlm; או פקס <span>03-3094095,</span>&rlm; בשני הנושאים ניתן גם לחייג&rlm; <span>0051*</span>&rlm; או &rlm;לפנות באופן מקוון באתר או לכתובת המופיעה בראש החשבונית.</p>
									<p>השירותים המפורטים בחשבון זה מסופקים על ידי מרתון&rlm; 018 אקספון בע״מ (ח.פ.  515138089) (״מרתון״) מכוח רישיונה. חיוב וגביית התשלומים בגין השירותים נעשה על ידי אקספון 018 בע״מ, לטובת מרתון.</p>
								</td>
							</tr>
						</tfoot>
					</table>
				</div>
			</footer>
		</div>
	</body>

</html>
