version: '3.7'

services:
    web:
        image: nginx:latest
        container_name: billrun-nginx
        ports:
            - "8080:80"
        restart: always
        volumes:
            - ${PWD}/../..:/billrun:ro
            - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - "php"
            - "mongodb"
        environment:
        - "APPLICATION_ENV=container"    
    php:
        build: 
            context: ./billrun-php7
            dockerfile: Dockerfile-php73
        image: billrun-php73
        container_name: billrun-app
        restart: always
        environment:
        - "APPLICATION_ENV=container"
        - "XDEBUG_CONFIG=client_host=10.103.0.1 client_port=9090 mode=develop"
        volumes:
            - ${PWD}/../..:/billrun
        command: sh -c "composer update && php-fpm "
    mongodb:
        image: mongo:3.6
        container_name: billrun-mongodb
        restart: always
        volumes:
            - ${PWD}/../..:/billrun:ro
            # - ${PWD}/../persist/data/db/mongo-3.6:/data/db
            # - ${PWD}/../persist/backup:/backup
            - ${PWD}/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
        ports:
            - 27018:27017
    chrome:
        image: selenium/standalone-chrome
        container_name: billrun-standalone-chrome
        restart: always

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.1/16
