services:
    web:
        image: nginx:latest
        container_name: billrun-nginx
        ports:
            - "8074:80"
        restart: always
        user: "${USER_ID:-0}:${GROUP_ID:-0}"
        volumes:
            - ${PWD}/../..:/billrun:ro
            - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - "php"
            - "mongodb"
        environment:
        - "APPLICATION_ENV=container"    
    php:
        build: 
            context: ./billrun-php74
            dockerfile: Dockerfile
        image: billrun-php74
        container_name: billrun-app
        restart: always
        user: "${USER_ID:-0}:${GROUP_ID:-0}"
        environment:
        - "APPLICATION_ENV=container"
        - "XDEBUG_CONFIG=client_host=10.103.0.1 client_port=9090 mode=develop"
        - "BR_MDB_HOST=billrun-mongodb:27017"
        - "BR_MDB_DBNAME=billing_container"
        - "COMPOSER_HOME=/tmp/composer"
        volumes:
            - ${PWD}/../..:/billrun
            - ./../../cache:/billrun/cache
            - ${PLUGIN_PATH:-/dev/null}:/plugin
        healthcheck:
            test: ["CMD-SHELL", "test -f /billrun/vendor/bin/codecept || exit 1"]
            interval: 20s
            timeout: 3s
            retries: 4
        command: sh -c "mkdir -p /billrun/vendor && cp -r /var/www/html/vendor/* /billrun/vendor/ && php-fpm"
    mongodb:
        image: mongo:3.6
        container_name: billrun-mongodb
        restart: always
        volumes:
            - ${PWD}/../..:/billrun:ro
            # - ${PWD}/../persist/data/db/mongo-3.6:/data/db
            # - ${PWD}/../persist/backup:/backup
            - ${PWD}/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
            - ${PLUGIN_PATH:-/dev/null}:/plugin
        ports:
            - 27017:27017
    chrome:
        image: selenium/standalone-chrome
        container_name: billrun-standalone-chrome
        restart: always
    mockup:
        build:
            context: ./mockup-servers
            dockerfile: Dockerfile-webserver
        container_name: billrun-mockups
        environment:
        - "XDEBUG_CONFIG=client_host=10.103.0.1 client_port=9090 discover_client_host=false mode=develop"
        volumes:
            - ${PWD}/mockup-servers:/mockups
            - ${PLUGIN_PATH:-/dev/null}:/plugin
        command: php -S 0.0.0.0:8081 router.php
        ports:
        - 8081:8081
        restart: always
        networks:
            default:
                ipv4_address: 10.103.0.10

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.0/16

