<form action="/utest/result" method="<?php echo $request_method ?>" class="form-horizontal">
	<input type="hidden" name="type" value="addCharge" >
	<div class="form-group row">
		<label for="sid" class="col-sm-2 control-label text-right">SID</label>
		<div class="col-sm-5">
			<input type="text" name="sid" value='<?php echo $sid ?>'  class="form-control">
		</div>
	</div>
	<div class="form-group row">
		<label for="balanceType" class="col-sm-2 control-label text-right">Charging Name</label>
		<div class="col-sm-5">
			<select class="form-control" name='balanceType'>
				<?php foreach ($balance_types['plans'] as $balance_type) : ?>
					<option value="<?php echo $balance_type['name'] ?>"><?php echo $balance_type['name'] . " | " . $balance_type['service_provider'] . " - " . $balance_type['desc'] ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>
	<div class="form-group row">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Add Charge</button>
		</div>
	</div>
</form>