<form action="/utest/result" method="<?php echo $request_method ?>" class="form-horizontal">

	<input type="hidden" name="type" value="<?php echo $name ?>" >
	<input type="hidden" name="testcollection" value="<?php echo $test_collection ?>" >

	<div class="form-group row">
		<dl class="col-sm-12 text-center">
			<dt><?php echo $label ?></dt>
			<dd>Set subscriber’s auto renew services (such periodic charges). The recurring manage by the billing engine</dd>
		</dl>
	</div>
	<hr/>

	<div class="form-group row">
		<label for="sid" class="col-sm-4 control-label text-right">SID</label>
		<div class="col-sm-6">
			<input type="text" name="sid" value='<?php echo $sid ?>'  class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="plan" class="col-sm-4 control-label text-right">Plan</label>
		<div class="col-sm-6">
			<select class="form-control" name='plan'>
				<?php foreach ($autorenew_plans as $autorenew_plan) : ?>
					<option value="<?php echo $autorenew_plan['name'] ?>"><?php echo $autorenew_plan['service_provider'] ?> | <?php echo $autorenew_plan['name'] ?> (exp.<?php echo $autorenew_plan['exp'] ?>) </option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>

	<div class="form-group row required">
		<label for="from" class="col-sm-4 control-label text-right">From</label>
		<div class="col-sm-6">
			<div class='input-group datetimepicker'>
				<input type='text' class="form-control" value="<?php echo date('d-m-Y H:i') ?>" name='from'/>
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-calendar"></span>
				</span>
			</div>
		</div>
	</div>

	<div class="form-group row required">
		<label for="to" class="col-sm-4 control-label text-right">To</label>
		<div class="col-sm-6">
			<div class='input-group datetimepicker'>
				<input type='text' class="form-control" value="<?php echo date('d-m-Y H:i') ?>" name='to'/>
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-calendar"></span>
				</span>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="interval" class="col-sm-4 control-label text-right">Interval</label>
		<div class="col-sm-6">
			<select class="form-control" name='interval'>
				<option value="day">Day</option>
				<option value="week">Week</option>
				<option value="month" selected>Month</option>
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label for="operation" class="col-sm-4 control-label text-right">Operation</label>
		<div class="col-sm-6">
			<select class="form-control" name='operation'>
				<option value="set">SET</option>
				<option value="inc" selected>INC</option>
			</select>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-offset-4 col-sm-6">
			<button type="submit" class="btn btn-success btn-block">Run Test</button>
		</div>
	</div>

</form>