<form action="/utest/result" method="<?php echo $request_method ?>" class="form-horizontal">
	<input type="hidden" name="type" value="<?php echo $name ?>" >

	<div class="form-group row">
		<dl class="col-sm-7 text-center">
			<dt>API Update Balance by Card</dt>
			<!--<dd></dd>-->
		</dl>
	</div>
	<hr/>

	<div class="form-group row">
		<label for="sid" class="col-sm-2 control-label text-right">SID</label>
		<div class="col-sm-5">
			<input type="text" name="sid" value='<?php echo $sid ?>'  class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="amount" class="col-sm-2 control-label text-right">Secret</label>
		<div class="col-sm-5">
			<input type="text" name="secret" class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Add Balance</button>
		</div>
	</div>
</form>