<form action="/utest/result?collection=<?php echo $test_collection ?>" method="<?php echo $request_method ?>" class="form-horizontal">

	<input type="hidden" name="type" value="<?php echo $name ?>" >
	<input type="hidden" name="testcollection" value="<?php echo $test_collection ?>" >

	<div class="form-group row">
		<dl class="col-sm-12 text-center">
			<dt><?php echo $label ?></dt>
			<dd></dd>
		</dl>
	</div>
	<hr/>

	<div class="form-group row">
		<label for="sid" class="col-sm-4 control-label text-right">SID</label>
		<div class="col-sm-6">
			<input type="text" name="sid" value='<?php echo $sid ?>'  class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="balanceType" class="col-sm-4 control-label text-right">Charging Name</label>
		<div class="col-sm-6">
			<select class="form-control" name='balanceType'>
				<?php foreach ($charging_plans as $charging_plan) : ?>
					<option value="<?php echo $charging_plan['name'] ?>"><?php echo $charging_plan['name'] . " | " . $charging_plan['service_provider'] . " - " . $charging_plan['desc'] ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label for="operation" class="col-sm-4 control-label text-right">Operation</label>
		<div class="col-sm-6">
			<!--<input type="text" name="operation" value=''  class="form-control">-->
			<select name="operation" value=''  class="form-control">
				<option value="" selected="selected">default</option>
				<option value="inc">inc</option>
				<option value="set">set</option>
				<option value="new">new</option>
			</select>
		</div>
	</div>
	
	<div class="form-group row">
		<div class="col-sm-offset-4 col-sm-6">
			<button type="submit" class="btn btn-success btn-block">Run Test</button>
		</div>
	</div>

</form>