<form action="/utest/result" method="<?php echo $request_method ?>" class="form-horizontal">

	<input type="hidden" name="type" value="<?php echo $name ?>" >
	<input type="hidden" name="testcollection" value="<?php echo $test_collection ?>" >

	<div class="form-group row">
		<dl class="col-sm-12 text-center">
			<dt><?php echo $label ?></dt>
			<dd></dd>
		</dl>
	</div>
	<hr/>

	<div class="form-group row">
		<label for="sid" class="col-sm-4 control-label text-right">SID</label>
		<div class="col-sm-6">
			<input type="text" name="sid" value='<?php echo $sid ?>'  class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="amount" class="col-sm-4 control-label text-right">Secret</label>
		<div class="col-sm-6">
			<input type="text" name="secret" class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-offset-4 col-sm-6">
			<button type="submit" class="btn btn-success btn-block">Run Test</button>
		</div>
	</div>

</form>