<form action="/utest/result?collection=<?php echo $test_collection?>" method="<?php echo $request_method ?>" class="form-horizontal">
	
	<input type="hidden" name="type" value="<?php echo $name ?>">
	<input type="hidden" name="testcollection" value="<?php echo $test_collection ?>" >

	<div class="form-group row">
		<dl class="col-sm-12 text-center">
			<dt><?php echo $label ?></dt>
			<dd></dd>
		</dl>
	</div>
	<hr/>

	<div class="form-group row">
		<label for="imsi" class="col-sm-4 control-label text-right">IMSI</label>
		<div class="col-sm-6">
			<input type="text" name="imsi" value='<?php echo $imsi ?>' class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="dialedDigits" class="col-sm-4 control-label text-right">Dialed Digits</label>
		<div class="col-sm-6">
			<input type="text" name="dialedDigits" value='<?php echo $dialed_digits ?>' class="form-control">
		</div>
	</div>
	
	<div class="form-group row">
		<label for="scenario" class="col-sm-4 text-right">Scenario</label>
		<div class="col-sm-6">
			<textarea rows="6" name="scenario" class="form-control" ><?php echo $call_scenario ?></textarea>
			<small class="text-muted">[ACTION_NAME|DURATION] New line per action, Default call duration is 4000.</small>
		</div>
	</div>
	
	<div class="form-group row">
		<label for="time_date" class="col-sm-4 control-label text-right">Call Start Time</label>
		<div class="col-sm-6">
			<div class='input-group datetimepicker'>
				<input type='text' class="form-control" value="<?php echo date('d/m/Y H:i') ?>" name='time_date'/>
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-calendar"></span>
				</span>
			</div>
		</div>
	</div>
	
	<div class="form-group row">
		<label for="np_code" class="col-sm-4 control-label text-right">NP Code</label>
		<div class="col-sm-6">
			<div class="input-group">
				<span class="input-group-addon">
					<input type="checkbox" class='enable-input' name="send_np_code">
					<small class="text-muted text-center">Check to send value.</small>
				</span>
				<select class="form-control" name='np_code'>
					<option value=""></option>
					<?php foreach ($np_codes as $np_code) : ?>
						<option value="<?php echo $np_code ?>"><?php echo $np_code ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<label class="col-sm-4 text-right"></label>
		<div class="col-sm-6">
			<div class="checkbox">
				<label>
					<input type="checkbox" name="removeLines" value="remove">Remove all existing lines for this imsi
				</label>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-offset-4 col-sm-6">
			<button type="submit" class="btn btn-success btn-block">Run Test</button>
		</div>
	</div>
	
</form>