<form action="/utest/result?collection=<?php echo $test_collection ?>" method="<?php echo $request_method ?>" class="form-horizontal">

	<input type="hidden" name="type" value="<?php echo $name ?>">
	<input type="hidden" name="testcollection" value="<?php echo $test_collection ?>" >

	<div class="form-group row">
		<dl class="col-sm-12 text-center">
			<dt><?php echo $label ?></dt>
			<dd>Notify Billrun on prepaid origination call scenarios, according to client’s engineering specification: “Prepaid Origination Call Scenarios”. If subscriber is eligible for the call, lines are inserted into Billrun. Otherwise, returns an indication.</dd>
		</dl>
	</div>
	<hr/>

	<div class="form-group row">
		<span  class="col-sm-4 control-label text-right"></span>
		<!--<label for="call_tech" class="col-sm-4 control-label text-right">Call Tech</label>-->
		<div class="col-sm-6">
			<label class="radio-inline">
				<input type="radio" name="call_tech" value="UMTS" class="hierarchical" data-require-pair="#choice-imsi" checked>UMTS</label>
			<label class="radio-inline">
				<input type="radio" name="call_tech" value="CDMA" class="hierarchical" data-require-pair="#choice-calling_number">CDMA</label>
		</div>
	</div>

	<div class="form-group row">

		<div class="hierarchical-dependency call_tech" id="choice-calling_number">
			<label for="msisdn" class="col-sm-4 control-label text-right">Calling Number</label>
			<div class="col-sm-6 require-if-active">
				<input type="text" name="msisdn" value='' class="form-control">
				<small class="text-muted">MSISDN</small>
			</div>
		</div>

		<div class="hierarchical-dependency call_tech" id="choice-imsi">
			<label for="imsi" class="col-sm-4 control-label text-right">IMSI</label>
			<div class="col-sm-6 require-if-active">
				<input type="text" name="imsi" value='' class="form-control">
				<small class="text-muted">42503xxxxxxxxxx / 42514xxxxxxxxxx – 15 digits</small>
			</div>
		</div>	

	</div>

	<div class="form-group row">
		<label for="called_number" class="col-sm-4 control-label text-right">Called Number</label>
		<div class="col-sm-6">
			<input type="text" name="called_number" value='<?php echo $dialed_digits ?>' class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="msc" class="col-sm-4 control-label text-right">MSC</label>
		<div class="col-sm-6">
			<input type="text" name="msc" value='<?php echo $msc ?>' class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="scenario" class="col-sm-4 text-right">Scenario</label>
		<div class="col-sm-6">
			<textarea rows="6" name="scenario" class="form-control" ><?php echo $call_scenario ?></textarea>
			<small class="text-muted"><strong>[ACTION_NAME|DURATION_SECONDS]</strong> New line per action.
				<br/>* ACTION_NAME : start_call / answer_call / reservation_time / release_call
				<br/>* DURATION_SECONDS : seconds, default call duration is 480 seconds.
			</small>
		</div>
	</div>

	<div class="form-group row">
		<label for="call_type" class="col-sm-4 control-label text-right">Call Type</label>
		<div class="col-sm-6">
			<select class="form-control" name='call_type'>
				<option value="0">Free</option>
				<option value="1" selected>National</option>
				<option value="2">International</option>
				<option value="3">Video</option>
				<option value="10">Roaming incoming</option>
				<option value="11">Roaming call to Israel</option>
				<option value="12">Roaming call abroad</option>
				<option value="13">Roaming callback</option>
				<option value="14">Roaming callback short</option>
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label class="col-sm-4 control-label text-right" for="time_date">Call Start Time</label>
		<div class="col-sm-6">
			<div class="input-group">
				<div class="input-group-addon">
					<input type="checkbox" class='enable-input' name="send_time_date">
					<small class="text-muted text-center">Check to send value.</small>
				</div>
				<div class='col-sm-12 input-group datetimepicker'>
					<input type='text' class="form-control" value='' name='time_date'/>
					<span class="input-group-addon">
						<span class="glyphicon glyphicon-calendar"></span>
					</span>
				</div>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<label class="col-sm-4 control-label text-right">Mode</label>
		<div class="col-sm-6">
			<div class="input-group">
				<span class="input-group-addon">
					<input type="checkbox" class='enable-input' name="send_mode">
					<small class="text-muted text-center">Check to send value.</small>
				</span>
				<select class="form-control" name='mode' data-default="sync">
					<option value="sync">Sync</option>
					<option value="async">Async</option>
				</select>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="np_code" class="col-sm-4 control-label text-right">NP Code</label>
		<div class="col-sm-6">
			<div class="input-group">
				<span class="input-group-addon">
					<input type="checkbox" class='enable-input' name="send_np_code" checked>
					<small class="text-muted text-center">Check to send value.</small>
				</span>
				<select class="form-control" name='np_code'>
					<option value=""></option>
					<?php foreach ($np_codes as $np_code) : ?>
						<?php $npcode = explode("|", $np_code) ?>
						<option value="<?php echo $npcode[0] ?>">(<?php echo $npcode[0] ?>) <?php echo $npcode[1] ?> </option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>
	</div>
	<!--
		<div class="form-group row">
			<label class="col-sm-4 text-right"></label>
			<div class="col-sm-6">
				<div class="checkbox">
					<label>
						<input type="checkbox" name="removeLines" value="remove">Remove all existing lines for this Calling Number before running test
					</label>
				</div>
			</div>
		</div>-->

	<div class="form-group row">
		<div class="col-sm-offset-4 col-sm-6">
			<button type="submit" class="btn btn-success btn-block">Run Test</button>
		</div>
	</div>

</form>