<form action="/utest/result" method="<?php echo $request_method ?>" class="form-horizontal">
	<input type="hidden" name="type" value="<?php echo $name ?>">

	<div class="form-group row">
		<dl class="col-sm-8 text-center">
			<dt>Cards Delete</dt>
			<dd>Delete one or range of cards by each of the query fields. batch_number is required</dd>
		</dl>
	</div>
	<hr/>

	<div class="form-group row">
		<label for="secret" class="col-sm-3 control-label text-right">Secret</label>
		<div class="col-sm-5">
			<input type="text" name="secret" value=''  class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="serial_number" class="col-sm-3 control-label text-right">Serial Number</label>
		<div class="col-sm-5">
			<input type="text" name="serial_number" value=''  class="form-control">
		</div>
	</div>

	<div class="form-group row required">
		<label for="batch_number" class="col-sm-3 control-label text-right">Batch Number</label>
		<div class="col-sm-5">
			<input type="text" name="batch_number" value=''  class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="status" class="col-sm-3 control-label text-right">Status</label>
		<div class="col-sm-5">
			<select class="form-control" name='status'>
				<option value=""></option>
				<?php foreach ($card_statuses as $card_status) : ?>
					<option value="<?php echo $card_status ?>"><?php echo $card_status ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-offset-3 col-sm-10">
			<button type="submit" class="btn btn-success">Start Test</button>
		</div>
	</div>
</form>