<form action="/utest/result?collection=<?php echo $test_collection ?>" method="<?php echo $request_method ?>" class="form-horizontal">

	<input type="hidden" name="type" value="<?php echo $name ?>">
	<input type="hidden" name="testcollection" value="<?php echo $test_collection ?>" >

	<div class="form-group row">
		<dl class="col-sm-12 text-center">
			<dt><?php echo $label ?></dt>
			<dd></dd>
		</dl>
	</div>
	<h3><small>Query</small></h3>
	<hr/>

	<div class="form-group row">
		<label for="secret" class="col-sm-4 control-label text-right">Secret</label>
		<div class="col-sm-6">
			<input type="text" name="secret" value=''  class="form-control">
		</div>
	</div>

	<div class="form-group row required">
		<label for="serial_number" class="col-sm-4 control-label text-right">Serial Number</label>
		<div class="col-sm-6">
			<input type="text" name="serial_number" value=''  class="form-control">
		</div>
	</div>

	<div class="form-group row required">
		<label for="batch_number" class="col-sm-4 control-label text-right">Batch Number</label>
		<div class="col-sm-6">
			<input type="text" name="batch_number" value=''  class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="status" class="col-sm-4 control-label text-right">Status</label>
		<div class="col-sm-6">
			<select class="form-control" name='status'>
				<option value=""></option>
				<?php foreach ($card_statuses as $card_status) : ?>
					<option value="<?php echo $card_status ?>"><?php echo $card_status ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>

	<h3><small>Update</small></h3>
	<hr/>

	<div class="form-group row">
		<label for="new_status" class="col-sm-4 control-label text-right">Status</label>
		<div class="col-sm-6">
			<div class="input-group">
				<span class="input-group-addon">
					<input type="checkbox" class='enable-input' name="send_new_status">
					<small class="text-muted text-center">Check to send value.</small>
				</span>
				<select class="form-control" name='new_status'>
					<option value=""></option>
					<?php foreach ($card_statuses as $card_status) : ?>
						<option value="<?php echo $card_status ?>"><?php echo $card_status ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="new_batch_number" class="col-sm-4 control-label text-right">Batch Number</label>
		<div class="col-sm-6">
			<div class="input-group">
				<span class="input-group-addon">
					<input type="checkbox" class='enable-input' name="send_new_batch_number">
					<small class="text-muted text-center">Check to send value.</small>
				</span>
				<input type="text" name="new_batch_number" value=''  class="form-control">
			</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="new_serial_number" class="col-sm-4 text-right">Serial Number</label>
		<div class="col-sm-6">
			<div class="input-group">
				<span class="input-group-addon">
					<input type="checkbox" class='enable-input' name="send_new_serial_number">
					<small class="text-muted text-center">Check to send value.</small>
				</span>
				<input type="text" name="new_serial_number" value='' class="form-control">
			</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="new_service_provider" class="col-sm-4 control-label text-right">Service Provider</label>
		<div class="col-sm-6">
			<div class="input-group">
				<span class="input-group-addon">
					<input type="checkbox" class='enable-input' name="send_new_service_provider">
					<small class="text-muted text-center">Check to send value.</small>
				</span>
				<select class="form-control" name='new_service_provider'>
					<option value=""></option>
					<?php foreach ($service_providers as $service_provider) : ?>
						<option value="<?php echo $service_provider ?>"><?php echo $service_provider ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-4 control-label text-right" for="new_expiration">Expiration Date</label>
		<div class="col-sm-6">
			<div class="input-group">
				<div class="input-group-addon">
					<input type="checkbox" class='enable-input' name="send_new_expiration">
					<small class="text-muted text-center">Check to send value.</small>
				</div>
				<div class='col-sm-12 input-group datetimepicker'>
					<input type='text' class="form-control" value='' name='new_expiration'/>
					<span class="input-group-addon">
						<span class="glyphicon glyphicon-calendar"></span>
					</span>
				</div>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="new_paln" class="col-sm-4 control-label text-right">Charging Name</label>
		<div class="col-sm-6">
			<div class="input-group">
				<span class="input-group-addon">
					<input type="checkbox" class='enable-input' name="send_new_paln">
					<small class="text-muted text-center">Check to send value.</small>
				</span>
				<select class="form-control" name='new_paln'>
					<option value=""></option>
					<?php foreach ($charging_plans as $charging_plan) : ?>
						<option value="<?php echo $charging_plan['name'] ?>"><?php echo $charging_plan['name'] . " (" . $charging_plan['service_provider'] . ")" ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-offset-4 col-sm-6">
			<button type="submit" class="btn btn-success btn-block">Run Test</button>
		</div>
	</div>

</form>