<form action="/utest/result" method="<?php echo $request_method ?>" class="form-horizontal">

	<input type="hidden" name="type" value="<?php echo $name ?>">

	<div class="form-group row">
		<dl class="col-sm-12 text-center">
			<dt><?php echo $label ?></dt>
			<dd></dd>
		</dl>
	</div>
	<hr/>

	<div class="form-group row">
		<label for="imsi" class="col-sm-4 control-label text-right">IMSI</label>
		<div class="col-sm-6">
			<input type="text" name="imsi" value='<?php echo $imsi ?>' class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="scenario" class="col-sm-4 text-right">Scenario</label>
		<div class="col-sm-6">
			<textarea rows="6" name="scenario" class="form-control"><?php echo $data_scenario ?></textarea>
			<small class="text-muted">[ACTION_NAME|USAGE] New line per action, Default data usage is 1000.</small>
		</div>
	</div>

	<div class="form-group row">
		<label class="col-sm-4"></label>
		<div class="col-sm-6">
			<div class="checkbox">
				<label>
					<input type="checkbox" name="removeLines" value="remove" checked>Remove all existing lines for this imsi
				</label>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-offset-4 col-sm-6">
			<button type="submit" class="btn btn-success btn-block">Run Test</button>
		</div>
	</div>

</form>