<form action="/utest/result" method="<?php echo $request_method ?>" class="form-horizontal">
	<input type="hidden" name="type" value="<?php echo $name ?>">

	<div class="form-group row">
		<label for="calling_number" class="col-sm-2 control-label text-right">Calling Number</label>
		<div class="col-sm-5">
			<input type="text" name="msisdn" value='' class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="called_number" class="col-sm-2 control-label text-right">Called Number</label>
		<div class="col-sm-5">
			<input type="text" name="called_number" value='' class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="source_system" class="col-sm-2 control-label text-right">Source System</label>
		<div class="col-sm-5">
			<select class="form-control" name='source_system'>
				<option value="TMM">TMM</option>
				<option value="SMSC">SMSC</option>
				<option value=""></option>
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label for="usaget" class="col-sm-2 control-label text-right">SMS/MMS</label>
		<div class="col-sm-5">
			<select class="form-control" name='usaget'>
				<option value="sms">SMS</option>
				<option value="mms">MMS</option>
			</select>
		</div>
	</div>
	
	<div class="form-group row">
		<label class="col-sm-2"></label>
		<div class="col-sm-5">
			<div class="checkbox">
				<label>
					<input type="checkbox" name="removeLines" value="remove" checked>Remove all existing lines for this Calling Number before running test
				</label>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Start Test</button>
		</div>
	</div>
</form>