<form action="/utest/result?collection=<?php echo $test_collection?>" method="<?php echo $request_method ?>" class="form-horizontal">

	<input type="hidden" name="type" value="<?php echo $name ?>">
	<input type="hidden" name="testcollection" value="<?php echo $test_collection ?>" >

	<div class="form-group row">
		<dl class="col-sm-12 text-center">
			<dt><?php echo $label ?></dt>
			<dd></dd>
		</dl>
	</div>
	<hr/>

	<div class="form-group row">
		<label for="calling_number" class="col-sm-4 control-label text-right">Calling Number</label>
		<div class="col-sm-6">
			<input type="text" name="msisdn" value='' class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="called_number" class="col-sm-4 control-label text-right">Called Number</label>
		<div class="col-sm-6">
			<input type="text" name="called_number" value='' class="form-control">
		</div>
	</div>

	<div class="form-group row">
		<label for="source_system" class="col-sm-4 control-label text-right">Source System</label>
		<div class="col-sm-6">
			<select class="form-control" name='source_system'>
				<option value="TMM">TMM</option>
				<option value="SMSC">SMSC</option>
				<option value=""></option>
			</select>
		</div>
	</div>

	<div class="form-group row">
		<label for="usaget" class="col-sm-4 control-label text-right">SMS/MMS</label>
		<div class="col-sm-6">
			<select class="form-control" name='usaget'>
				<option value="sms">SMS</option>
				<option value="mms">MMS</option>
			</select>
		</div>
	</div>
	
	<div class="form-group row">
		<label for="send_faild_request" class="col-sm-4 control-label text-right">Failed SMS</label>
		<div class="col-sm-6">
			<div class="checkbox">
				<label>
					<input type="checkbox" name="send_faild_request" value="send_faild_request">Check to simulate failed SMS
				</label>
			</div>
		</div>
	</div>
	
	<div class="form-group row">
		<label class="col-sm-4"></label>
		<div class="col-sm-6">
			<div class="checkbox">
				<label>
					<input type="checkbox" name="removeLines" value="remove">Remove all existing lines for this Calling Number before running test
				</label>
			</div>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-offset-4 col-sm-6">
			<button type="submit" class="btn btn-success btn-block">Run Test</button>
		</div>
	</div>

</form>