<form action="/utest/result" method="<?php echo $request_method ?>" class="form-horizontal">
	<input type="hidden" name="type" value="<?php echo $name ?>">
	
	<h3>Search by :</h3>
	<div class="form-group row">
		<label for="sid" class="col-sm-2 control-label text-right">SID</label>
		<div class="col-sm-5">
			<input type="text" name="sid" value='<?php echo $sid ?>'  class="form-control">
		</div>
	</div>
	<div class="form-group row">
		<label for="imsi" class="col-sm-2 control-label text-right">IMSI</label>
		<div class="col-sm-5">
			<input type="text" name="imsi" value='<?php echo $imsi ?>'  class="form-control">
		</div>
	</div>
	<div class="form-group row">
		<label for="msisdn" class="col-sm-2 control-label text-right">MSISDN</label>
		<div class="col-sm-5">
			<input type="text" name="msisdn" value=''  class="form-control">
		</div>
	</div>
	
	<h3>Update :</h3>
	<div class="form-group row">
		<label for="new_sid" class="col-sm-2 control-label text-right">SID</label>
		<div class="col-sm-5">
			<div class="input-group">
			<span class="input-group-addon">
				<input type="checkbox" class='enable-input' name="enable-new_sid">
				<small class="text-muted text-center">Check to send value.</small>
			</span>
			<input type="text" name="new_sid" value=''  class="form-control">
		</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="new_imsi" class="col-sm-2 text-right">IMSI</label>
		<div class="col-sm-5">
			<div class="input-group">
			<span class="input-group-addon">
				<input type="checkbox" class='enable-input' name="enable-new_imsi">
				<small class="text-muted text-center">Check to send value.</small>
			</span>
			<textarea rows="4" name="new_imsi" class="form-control" ></textarea>
			<small class="text-muted">New line per IMSI.</small>
		</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="new_msisdn" class="col-sm-2 control-label text-right">MSISDN</label>
		<div class="col-sm-5">
			<div class="input-group">
			<span class="input-group-addon">
				<input type="checkbox" class='enable-input' name="enable-new_msisdn">
				<small class="text-muted text-center">Check to send value.</small>
			</span>
			<input type="text" name="new_msisdn" value='' class="form-control">
		</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="aid" class="col-sm-2 control-label text-right">AID</label>
		<div class="col-sm-5">
			<div class="input-group">
			<span class="input-group-addon">
				<input type="checkbox" class='enable-input' name="enable-aid">
				<small class="text-muted text-center">Check to send value.</small>
			</span>
			<input type="text" name="aid" value='' class="form-control">
		</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="plan" class="col-sm-2 control-label text-right">Plan</label>
		<div class="col-sm-5">
			<div class="input-group">
			<span class="input-group-addon">
				<input type="checkbox" class='enable-input' name="enable-plan">
				<small class="text-muted text-center">Check to send value.</small>
			</span>
			<select class="form-control" name='plan'>
				<option value=""></option>
				<?php foreach ($customer_plans as $customer_plan) : ?>
					<option value="<?php echo $customer_plan ?>"><?php echo $customer_plan ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="service_provider" class="col-sm-2 control-label text-right">Service Provider</label>
		<div class="col-sm-5">
			<div class="input-group">
			<span class="input-group-addon">
				<input type="checkbox" class='enable-input' name="enable-service_provider">
				<small class="text-muted text-center">Check to send value.</small>
			</span>
			<select class="form-control" name='service_provider'>
				<option value=""></option>
				<?php foreach ($service_providers as $service_provider) : ?>
					<option value="<?php echo $service_provider ?>" <?php if ('Pelephone' == $service_provider) echo 'selected' ?>><?php echo $service_provider ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="charging_type" class="col-sm-2 control-label text-right">Charging Type</label>
		<div class="col-sm-5">
			<div class="input-group">
			<span class="input-group-addon">
				<input type="checkbox" class='enable-input' name="enable-charging_type">
				<small class="text-muted text-center">Check to send value.</small>
			</span>
			<select class="form-control" name='charging_type'>
				<option value=""></option>
				<?php foreach ($charging_types as $charging_type) : ?>
					<option value="<?php echo $charging_type ?>" <?php if ('prepaid' == $charging_type) echo 'selected' ?>><?php echo $charging_type ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		</div>
	</div>

	<div class="form-group row">
		<label for="language" class="col-sm-2 control-label text-right">Language</label>
		<div class="col-sm-5">
			<div class="input-group">
			<span class="input-group-addon">
				<input type="checkbox" class='enable-input' name="enable-language">
				<small class="text-muted text-center">Check to send value.</small>
			</span>
			<select class="form-control" name='language'>
				<?php foreach ($languages as $language) : ?>
					<option value="<?php echo $language ?>" <?php if ('Hebrew' == $language) echo 'selected' ?>><?php echo $language ?></option>
				<?php endforeach; ?>
				<option value=""></option>
			</select>
		</div>
		</div>
	</div>

	<div class="form-group row">
		<label class="col-sm-2 control-label text-right" >Track History</label>
		<div class="col-sm-5">
			<div class="input-group">
			<span class="input-group-addon">
				<input type="checkbox" class='enable-input' name="enable-track_history">
				<small class="text-muted text-center">Check to send value.</small>
			</span>
			<select class="form-control" name='track_history'>
					<option value="1" checked>True</option>
					<option value="">False</option>
			</select>
		</div>
		</div>
	</div>
	
	<div class="form-group row">
		<label class="col-sm-2 control-label text-right" >Keep Balances</label>
		<div class="col-sm-5">
			<div class="input-group">
			<span class="input-group-addon">
				<input type="checkbox" class='enable-input' name="enable-keep_balances">
				<small class="text-muted text-center">Check to send value.</small>
			</span>
			<select class="form-control" name='keep_balances'>
					<option value="1" checked>True</option>
					<option value="">False</option>
			</select>
		</div>
		</div>
	</div>
	
	<div class="form-group row">
		<label class="col-sm-2 control-label text-right" >Keep Lines</label>
		<div class="col-sm-5">
			<div class="input-group">
			<span class="input-group-addon">
				<input type="checkbox" class='enable-input' class='enable-input' name="enable-keep_lines">
				<small class="text-muted text-center">Check to send value.</small>
			</span>
			<select class="form-control" name='keep_lines'>
					<option value="1" checked>True</option>
					<option value="">False</option>
			</select>
		</div>
		</div>
	</div>
	

	<div class="form-group row">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Start Test</button>
		</div>
	</div>
</form>