<form action="/utest/result" method="get">
	<input type="hidden" name="type" value="data">
	<div class="form-group row">
		<label for="imsi" class="col-sm-2 form-control-label text-right">IMSI</label>
		<div class="col-sm-5">
			<input type="text" name="imsi" value='<?php echo $imsi ?>' class="form-control">
		</div>
	</div>
	<div class="form-group row">
		<label for="scenario" class="col-sm-2 form-control-label text-right">Scenario</label>
		<div class="col-sm-5">
			<textarea rows="6" name="scenario" class="form-control"><?php echo $data_scenario ?></textarea>
			<small class="text-muted">[ACTION_NAME|USAGE] New line per action, Default data usage is 1000.</small>
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-2"></label>
		<div class="col-sm-5">
			<div class="checkbox">
				<label>
					<input type="checkbox" name="removeLines" value="remove" checked>Remove all existing lines for this imsi
				</label>
			</div>
		</div>
	</div>
	<div class="form-group row">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Start Test</button>
		</div>
	</div>
</form>