<?php $colspan = empty($col_count) ? 1 : $col_count-1; ?>

<?php 
$displayTotal = FALSE;
if(!empty($data['discounts']['lines'])) {
	?>
	<?php foreach($data['discounts']['lines'] as $title => $amount) { ?>
	<?php
		if($amount == 0 ) { continue; }
		$displayTotal = TRUE;
	?>
		<tr class="total">
			<td colspan="<?php echo $colspan; ?>"><?php echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' . $title ?> </td>
			<td><?php echo '$' . number_format($amount,2) ?></td>
		</tr>
	<?php }//foreach ?>
	<?php if($displayTotal) { ?>
		<tr class="total">
			<td colspan='<?php echo $colspan; ?>'>TOTAL DISCOUNTS</td>
			<td><?php echo '$' . number_format($data['discounts']['total'] , 2); ?></td>
		</tr>
	<?php } ?>
<?php } ?>
