<?php //NOTE currently not in use as yaf  doesn't  support display priority
	//	 require to use instead of general layout (layout/menu.phtml) ?>
<div class="navbar-collapse collapse">
	<ul class="nav navbar-nav">
		<li<?php echo ($active == '' ? ' class="active"' : ''); ?>>
			<a href="<?php echo $this->baseUrl; ?>/admin">Home</a>
		</li>
		<?php if (AdminController::authorized('read', 'lines')) : ?>
			<li<?php echo ($active == 'lines' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/lines">Lines</a>
			</li>
		<?php endif; ?>
		<?php if (AdminController::authorized('read', 'queue')) : ?>
			<li<?php echo ($active == 'queue' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/queue">Queue</a>
			</li>
		<?php endif; ?>
		<?php if (AdminController::authorized('read', 'logs')) : ?>
			<li<?php echo ($active == 'logs' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/logs">Log</a>
			</li>
		<?php endif; ?>
		<?php if (AdminController::authorized('read','ipmapping')) : ?>
			<li<?php echo ($active == 'ipmapping' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/ipmapping">IP Mapping</a>
			</li>
		<?php endif; ?>
				<?php if (AdminController::authorized('admin')) : ?>
			<li class="dropdown<?php echo (in_array($active, array('users', 'config', 'operations')) ? ' active' : ''); ?>">
				<a class="dropdown-toggle"
				   data-toggle="dropdown"
				   href="#">
					Admin
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li<?php echo ($active == 'users' ? ' class="active"' : ''); ?>>
						<a href="<?php echo $this->baseUrl; ?>/admin/users">Users</a>
					</li>
				</ul>
			</li>
		<?php endif; ?>
		<?php if (Billrun_Factory::user() === FALSE) : ?>
			<li<?php echo ($active == 'login' ? ' class="login active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/login">Login</a>
			</li>
		<?php else: ?>
			<li class="logout">
				<a href="<?php echo $this->baseUrl; ?>/admin/logout">Logout</a>
			</li>
		<?php endif; ?>
			
	</ul>
</div><!--/.navbar-collapse -->
