<?php //NOTE currently not in use as yaf  doesn't  support display priority
	//	 require to use instead of general layout (layout/menu.phtml) ?>
<div class="navbar-collapse collapse">
	<ul class="nav navbar-nav">
		<li<?php echo ($active == '' ? ' class="active"' : ''); ?>>
			<a href="<?php echo $this->baseUrl; ?>/admin">Home</a>
		</li>
		<?php if (AdminController::authorized('read')) : ?>
			<li<?php echo ($active == 'lines' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/lines">Lines</a>
			</li>
			<li<?php echo ($active == 'plans' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/plans">Plans</a>
			</li>
			<li<?php echo ($active == 'rates' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/rates">Rates</a>
			</li>
			<li<?php echo ($active == 'balances' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/balances">Balances</a>
			</li>
                        <li<?php echo ($active == 'queue' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/queue">Queue</a>
			</li>
			<li<?php echo ($active == 'events' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/events">Events</a>
			</li>
			<li<?php echo ($active == 'log' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/log">Log</a>
			</li>
			<?php if (AdminController::authorized('reports')) : ?>
			<li<?php echo ($active == 'wholesale' ? ' class="active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/wholesale">Reports</a>
			</li>
			<?php endif; ?>
		<?php endif; ?>
		<?php if (AdminController::authorized('admin')) : ?>
			<li class="dropdown<?php echo (in_array($active, array('users', 'config')) ? ' active' : ''); ?>">
				<a class="dropdown-toggle"
				   data-toggle="dropdown"
				   href="#">
					Admin
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu"> 
					<li<?php echo ($active == 'config' ? ' class="active"' : ''); ?>>
						<a href="<?php echo $this->baseUrl; ?>/admin/config">Config</a>
					</li>
					<li<?php echo ($active == 'users' ? ' class="active"' : ''); ?>>
						<a href="<?php echo $this->baseUrl; ?>/admin/users">Users</a>
					</li>
					<li<?php echo ($active == 'operations' ? ' class="active"' : ''); ?>>
						<a href="<?php echo $this->baseUrl; ?>/admin/operations">Operations</a>
					</li>
				</ul>
			</li>
		<?php endif; ?>
		<?php if (Billrun_Factory::user() === FALSE) : ?>
			<li<?php echo ($active == 'login' ? ' class="login active"' : ''); ?>>
				<a href="<?php echo $this->baseUrl; ?>/admin/login">Login</a>
			</li>
		<?php else: ?>
			<li class="logout">
				<a href="<?php echo $this->baseUrl; ?>/admin/logout">Logout</a>
			</li>
		<?php endif; ?>
			
	</ul>
</div><!--/.navbar-collapse -->
