<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=1040" />
		<meta name="MobileOptimized" content="1040" />
		<link media="all" rel="stylesheet" href=<?php echo $this->css_path ?>>
		<script src="https://use.fontawesome.com/d996aff2f1.js"></script>
		<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700|Roboto:100,300,700" rel="stylesheet">
		<style type="text/css">
			.break{
				display: block;
				clear: both;
				page-break-after: always;
			}
		</style>
</head>
</head>
<body>
<?php
		print $this->render($this->sumup_template);
		print '<div class="break"></div>';
		print $this->render($this->details_template);
		print '<div class="break"></div>';
		print $this->render($this->lines_template);
?>
</body>
</html>

