<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=1040" />
		<meta name="MobileOptimized" content="1040" />
		<link media="all" rel="stylesheet" href=<?php echo $this->css_path ?> />
		<link rel="stylesheet" href=<?php echo $this->font_awesome_css_path; ?>/>
		<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700|Roboto:100,300,700" rel="stylesheet">
		<style type="text/css">
			.break{
				display: block;
				clear: both;
				page-break-after: always;
			}
		</style>
		<?php echo $tanent_css; ?>
</head>
</head>
<body>
	<div class="wrapper">
		<div class="shell">
			<div class="container">
<?php
		print $this->render($this->sumup_template);
		if($render_subscription_details) {
			$tabels = $this->createInvoiceTables($this->lines);
			print $this->render($this->details_template, $tabels);
		}
?>
			</div>
		</div>
	</div>
</body>
</html>

