<tr class="total">
	<td>TAXES</td>
	<td><?php echo '$' . number_format($data['after_vat'] - $data['before_vat'], 2); ?></td>
</tr>
<?php if(!empty($data['taxes'])) {	?>
	<?php foreach($data['taxes'] as $key => $taxAmount) { ?>
		<tr class="total">
			<td><?php echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' .ucfirst(strtolower($key)) ?> </td>
				<td><?php echo '$' . number_format($taxAmount,2) ?></td>
		</tr>
	<?php }//foreach ?>
<?php } ?>
