<div class="table table-default">
	<table>
		<thead>
			<tr>
				<th>Date &amp; Time</th>
				<th>Type</th>
				<th>Rate</th>
				<th>Volume</th>
				<th>Amount</th>
			</tr>
		</thead>

		<tbody>
			<?php if (!empty($lines)) { 
					$flippedKeys = array_flip($details_keys);
				?>			
				<?php foreach ($lines as $line) { ?>
					<?php if (!in_array($line['type'],$lines_detail_types)) { continue; } ?>
					<tr>
						<?php $billing_cycle_type = ["flat", "credit", "service"]?>
						<td><?php echo date($datetime_format, $line['urt']->sec - (in_array($line['type'], $billing_cycle_type) ? 1 : 0)); ?></td>
						<td><?php echo (!empty($flippedKeys[$line['usaget']]) ? $flippedKeys[$line['usaget']] : (empty($flippedKeys[$line['type']]) ? $line['type'] : $flippedKeys[$line['type']])) ; ?></td>
						<td><?php echo $this->getLineUsageName($line); ?></td>
						<td><?php echo $this->getLineUsageVolume($line); ?></td>
						<td><?php echo number_format($line['aprice'], 2); ?></td>
					</tr>
				<?php } ?>
			<?php } ?>
		</tbody>
	</table>
</div><!-- /.table table-default -->