<head>
	<meta charset="utf-8" />

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Billrun - Subscription payment page desktop</title>

	<!--<link rel="shortcut icon" type="image/x-icon" href="css/images/favicon.ico" />-->

	<!-- Vendor Styles -->
	<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i|Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

	<link rel="stylesheet" href="vendors/mCustomScrollbar/jquery.mCustomScrollbar.min.css" />

	<!-- App Styles -->
	<link rel="stylesheet" href="css/subpage_style.css" />

	<!-- Vendor JS -->
	<script src="js/vendor/jquery-1.12.4.min.js"></script>
	<script src="vendors/mCustomScrollbar/jquery.mCustomScrollbar.min.js"></script>

	<!-- App JS -->
	<script src="js/subpage_functions.js"></script>
</head>