			<div class="form-section form-section-solid">
				<div class="shell">
					<h5 class="form-subtitle">Total periodic fee</h5><!-- /.form-subtitle -->

					<div class="form-section-content">
						<div class="plan plan-alt">
							<div class="plan-body">
								<div class="plan-aside">
									Monthly charging
								</div><!-- /.plan-aside -->
							
								<div class="plan-content">
									<ul class="list-price">
										<li>
											<h2>$20.00</h2>

											<h6>1 first months</h6>
										</li>
										
										<li>
											<h2>$22.00</h2>

											<h6>2 next months</h6>
										</li>
										
										<li>
											<h2>$25.00</h2>

											<h6>3 months and on</h6>
										</li>
									</ul><!-- /.list-price -->
								</div><!-- /.plan-content -->
							</div><!-- /.plan-body -->
						</div><!-- /.plan -->
					</div><!-- /.form-section-content -->
				</div><!-- /.shell -->
			</div><!-- /.form-section -->
