<<?= "?" ?>xml version="1.0" encoding="UTF-16" ?>
<CallGeneratorReport>
	<From><?= date(Billrun_Base::base_dateformat,$from) ?></From>
	<To><?= date(Billrun_Base::base_dateformat, $to) ?></To>
	<Summary>
		<Missed><?= $summary['missed'] ?></Missed>
		<DurationDifference><?= $summary['duration_diff'] ?></DurationDifference>
		<CallTypes>
			<?php foreach ($summary['calls_types'] as $key => $value) {	?>
				<<?= ucfirst($key) ?>><?= $value ?></<?= ucfirst($key) ?>>
			<?php } ?>
		</CallTypes>
	<Summary>
	<Comparison>
		<?php foreach ($cdr_calls_comparison as $key => $value) {	?>
		<CallComparison>
			<CallTime><?= date(Billrun_Base::base_dateformat,$key*2)?></CallTime>
			<Generated>
				<?php if (isset($cdr_calls_comparison[$key]['generated'])) {	?>					
					<?php foreach ($cdr_calls_comparison[$key]['generated'] as $key => $value) {	?>
						<<?= ucfirst($key) ?>><?= $value ?></<?= ucfirst($key) ?>>
					<?php } ?>
				<?php } ?>								
			</Generated>
			<CDR>
				<?php if (isset($cdr_calls_comparison[$key]['cdr'])) {	?>
					<?php foreach ($cdr_calls_comparison[$key]['cdr'] as $key => $value) {	?>
						<<?= ucfirst($key) ?>><?= $value ?></<?= ucfirst($key) ?>>
					<?php } ?>
				<?php } ?>

			</CDR>
		</CallComparison>
		<?php } ?>

	</Comparison>
	<CallsBreakdown>
		<?php foreach ($generated_breakdown as $key => $value) { ?>
			<<?= ucfirst($key) ?>><?= count($value )?></<?= ucfirst($key) ?>>
		<?php } ?>
	</CallsBreakdown>
</CallGeneratorReport>