<!--
/**
 * @package         Billing
 * @copyright       Copyright (C) 2012 S.D.O.C. LTD. All rights reserved.
 * @license         GNU General Public License version 2 or later; see LICENSE.txt
 */
-->
<html>
	<head>
		<title><?php echo $this->title; ?></title>
		<link href="<?php echo $this->favicon; ?>" rel="shortcut icon" type="image/vnd.microsoft.icon" />
	</head>
	<body>
		<?php echo $this->content; ?>
	</body>
</html>