<!--
/**
 * @package         Billing
 * @copyright       Copyright (C) 2012 BillRun Technologies Ltd. All rights reserved.
 * @license         GNU Affero General Public License Version 3; see LICENSE.txt
 */
-->
<html>
	<head>
		<title><?php echo $this->title; ?></title>
		<link href="<?php echo $this->baseUrl; ?>/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />
	</head>
	<body>
		<?php echo $this->content; ?>
	</body>
</html>