;; Export Generators API Configuration

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; CREATE ACTION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
billapi.export_generators.create.permission="write"
billapi.export_generators.create.error_base=80000

billapi.export_generators.create.update_parameters.0.name=name
billapi.export_generators.create.update_parameters.0.type=string
billapi.export_generators.create.update_parameters.0.mandatory=1

billapi.export_generators.create.update_parameters.1.name=from
billapi.export_generators.create.update_parameters.1.type=datetime
billapi.export_generators.create.update_parameters.1.mandatory=0

billapi.export_generators.create.update_parameters.2.name=to
billapi.export_generators.create.update_parameters.2.type=datetime
billapi.export_generators.create.update_parameters.2.mandatory=0

billapi.export_generators.create.update_parameters.3.name=filtration
billapi.export_generators.create.update_parameters.3.type=json
billapi.export_generators.create.update_parameters.3.mandatory=0

billapi.export_generators.create.update_parameters.4.name=generator
billapi.export_generators.create.update_parameters.4.type=json
billapi.export_generators.create.update_parameters.4.mandatory=0

billapi.export_generators.create.update_parameters.5.name=frequency
billapi.export_generators.create.update_parameters.5.type=json
billapi.export_generators.create.update_parameters.5.mandatory=0

billapi.export_generators.create.update_parameters.6.name=senders
billapi.export_generators.create.update_parameters.6.type=json
billapi.export_generators.create.update_parameters.6.mandatory=0

billapi.export_generators.create.update_parameters.7.name=enabled
billapi.export_generators.create.update_parameters.7.type=bool
billapi.export_generators.create.update_parameters.7.mandatory=0 

billapi.export_generators.create.update_parameters.8.name=is_test_file
billapi.export_generators.create.update_parameters.8.type=bool
billapi.export_generators.create.update_parameters.8.mandatory=0 

billapi.export_generators.create.update_parameters.9.name=exporter
billapi.export_generators.create.update_parameters.9.type=json
billapi.export_generators.create.update_parameters.9.mandatory=0

billapi.export_generators.create.update_parameters.10.name=file_name
billapi.export_generators.create.update_parameters.10.type=string
billapi.export_generators.create.update_parameters.10.mandatory=0

billapi.export_generators.create.update_parameters.11.name=export_by_customer
billapi.export_generators.create.update_parameters.11.type=bool
billapi.export_generators.create.update_parameters.11.mandatory=0

billapi.export_generators.create.update_parameters.12.name=record_type_mapping
billapi.export_generators.create.update_parameters.12.type=json
billapi.export_generators.create.update_parameters.12.mandatory=0

billapi.export_generators.create.update_parameters.13.name=fields_mapping
billapi.export_generators.create.update_parameters.13.type=json
billapi.export_generators.create.update_parameters.13.mandatory=0

billapi.export_generators.create.update_parameters.14.name=header_mapping
billapi.export_generators.create.update_parameters.14.type=json
billapi.export_generators.create.update_parameters.14.mandatory=0

billapi.export_generators.create.update_parameters.15.name=footer_mapping
billapi.export_generators.create.update_parameters.15.type=json
billapi.export_generators.create.update_parameters.15.mandatory=0




;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; UPDATE ACTION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
billapi.export_generators.update.permission="write"
billapi.export_generators.update.error_base=80100

billapi.export_generators.update.unique_query_parameters=1

billapi.export_generators.update.update_parameters.0.name=filtration
billapi.export_generators.update.update_parameters.0.type=json

billapi.export_generators.update.update_parameters.1.name=generator
billapi.export_generators.update.update_parameters.1.type=json

billapi.export_generators.update.update_parameters.2.name=frequency
billapi.export_generators.update.update_parameters.2.type=json

billapi.export_generators.update.update_parameters.3.name=senders
billapi.export_generators.update.update_parameters.3.type=json

billapi.export_generators.update.update_parameters.4.name=enabled
billapi.export_generators.update.update_parameters.4.type=bool

billapi.export_generators.update.update_parameters.5.name=is_test_file
billapi.export_generators.update.update_parameters.5.type=bool

billapi.export_generators.update.update_parameters.6.name=exporter
billapi.export_generators.update.update_parameters.6.type=json

billapi.export_generators.update.update_parameters.7.name=file_name
billapi.export_generators.update.update_parameters.7.type=string

billapi.export_generators.update.update_parameters.8.name=export_by_customer
billapi.export_generators.update.update_parameters.8.type=bool

billapi.export_generators.update.update_parameters.9.name=record_type_mapping
billapi.export_generators.update.update_parameters.9.type=json

billapi.export_generators.update.update_parameters.10.name=fields_mapping
billapi.export_generators.update.update_parameters.10.type=json

billapi.export_generators.update.update_parameters.11.name=header_mapping
billapi.export_generators.update.update_parameters.11.type=json

billapi.export_generators.update.update_parameters.12.name=footer_mapping
billapi.export_generators.update.update_parameters.12.type=json

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; GET ACTION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
billapi.export_generators.get.permission="read"
billapi.export_generators.get.error_base=80400
billapi.export_generators.get.enable_sort=1
billapi.export_generators.get.restrict_query=0

billapi.export_generators.get.query_parameters.0.name=_id
billapi.export_generators.get.query_parameters.0.type=dbid

billapi.export_generators.get.query_parameters.1.name=name
billapi.export_generators.get.query_parameters.1.type=string


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; UNIQUE GET ACTION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
billapi.export_generators.uniqueget.permission="read"
billapi.export_generators.uniqueget.error_base=80200
billapi.export_generators.uniqueget.unique_query_parameters=1
billapi.export_generators.uniqueget.enable_sort=1


billapi.export_generators.uniqueget.restrict_query=0

billapi.export_generators.uniqueget.query_parameters.0.name=_id
billapi.export_generators.uniqueget.query_parameters.0.type=dbid

billapi.export_generators.uniqueget.query_parameters.1.name=name
billapi.export_generators.uniqueget.query_parameters.1.type=array


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; DELETE ACTION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
billapi.export_generators.delete.permission="write"
billapi.export_generators.delete.error_base=80300

billapi.export_generators.delete.query_parameters.0.name=_id
billapi.export_generators.delete.query_parameters.0.type=dbid
billapi.export_generators.delete.query_parameters.0.mandatory=1


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; COLLECTION-WIDE SETTINGS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

billapi.export_generators.active_documents=1

billapi.export_generators.collection_name="export_generators"

billapi.export_generators.duplicate_check[string]="name"
