<table class="complex-sumup">
	<thead>
		<tr>
			<th>Description</th>
			<th>Qty</th>
			<th>Rate</th>			
			<th>Amount</th>
		</tr>
	</thead>

	<tbody>
		<?php
			$subscriptionList = $this->buildSubscriptionListFromLines($this->lines);
			$endKey = end($subscriptionList);
			foreach ($subscriptionList as $key =>$aggregated) { ?>	
			<tr class="<?php echo ( $endKey === $key ? 'last' : '') ?>">
				<td class='desc'><?php echo ucfirst($aggregated['desc']); ?></td>
				<td class='qty'><?php echo $aggregated['count']; ?></td>
				<td class='rate'><?php echo number_format($aggregated['rate'],2); ?></td>
				<td class='amount'><?php echo '$' . number_format($aggregated['amount'], 2); ?></td>
			</tr>
		<?php } ?>
			
		<?php foreach ($details_keys as $title => $key) { ?>
			<?php if (empty($data->get('totals')[$key]) || in_array($key,$this->flat_line_types)) { continue; } ?>
			<tr class="<?php echo (end($details_keys) === $key ? 'last' : '') ?>">
				<td colspan="3"><?php echo ucfirst($title); ?></td>
				<td><?php echo '$' . number_format($data->get('totals')[$key]['before_vat'], 2); ?></td>
			</tr>
		<?php } ?>			
		<tr class="total">
			<td colspan="3">SUBTOTAL</td>
			<td><strong><?php echo '$' . number_format($data->get('totals')['before_vat'], 2); ?></strong></td>
		</tr>
		<?php echo $this->render($this->tax_template,array('data' => $data->get('totals'), 'col_count' => 4)); ?>

		<tr class="grand-total">
			<td colspan="3">GRAND TOTAL</td>
			<td><?php echo '$' . number_format($data->get('totals')['after_vat'], 2); ?></td>
		</tr>
	</tbody>
</table>