<table>
	<thead>
		<tr>
			<th><?php echo Generator_Translations::stranslate('Description');?></th>
			<th><?php echo Generator_Translations::stranslate('Amount');?></th>
		</tr>
	</thead>

	<tbody>

		<?php foreach ($details_keys as $title => $key) { ?>
			<?php if (empty($data->get('totals')[$key])) { continue; } ?>
			<tr class="<?php echo (end($details_keys) === $key ? 'last' : '') ?>">
				<td><?php echo Generator_Translations::stranslate(ucfirst($title)); ?></td>
				<td><?php echo $this->currencySymbol() . number_format($data->get('totals')[$key]['before_vat'], 2); ?></td>
			</tr>
		<?php } ?>

		<tr class="total">
			<td ><?php echo Generator_Translations::stranslate('SUBTOTAL');?></td>
			<td><strong><?php echo $this->currencySymbol() . number_format($data->get('totals')['before_vat'], 2); ?></strong></td>
		</tr>
		<?php echo $this->render($this->tax_template,array('data' => $data->get('totals'),'col_count'=>2))	?>
		
		<?php if (!empty($invoice_display_options['past_balance']) && $data->get('totals')['past_balance']['after_vat'] < -0.005) { ?>
			<tr class="total">
				<td colspan="1"><?php echo Generator_Translations::stranslate('PAST BALANCE / REIMBURSEMENTS');?></td>
				<td><?php echo $this->currencySymbol() . number_format($data->get('totals')['past_balance']['after_vat'], 2); ?></td>
			</tr>
		<?php } ?>

		<tr class="grand-total">
			<td colspan="1"><?php echo Generator_Translations::stranslate('GRAND TOTAL');?></td>
			<td><?php echo $this->currencySymbol() . number_format($data->get('totals')['after_vat']  + (!empty($invoice_display_options['past_balance']) ? $data->get('totals')['past_balance']['after_vat'] : 0 ), 2); ?></td>
		</tr>
	</tbody>
</table>
