<div class="section section-invoice-head">
	<table class="table-header">
		<tbody>
			<tr>
				<td>
					<h1>INVOICE</h1>
				</td>

				<td>
					<table class="table-inline">
						<tbody><tr>
								<td>Period</td>

								<td><strong>October 216</strong></td>
							</tr>

							<tr>
								<td>Invoice#</td>

								<td>100183</td>
							</tr>

							<tr>
								<td>Print Dte</td>

								<td>13/11/2016</td>
							</tr>
						</tbody></table>
				</td>
			</tr>
		</tbody>
	</table>
</div>
<section class="section-info">
	<table class="table-info">
		<tbody><tr>
				<td>
					<small>to</small>
				</td>

				<td>
					<h2>David Morison</h2>

					<span class="text">
						<small>Account</small>

						<span class="text">1244567</span>
					</span>
				</td>
			</tr>

			<tr>
				<td></td>

				<td>3455 Mount Zion St. New Jerssy</td>
			</tr>

			<tr>
				<td></td>

				<td>david.morison@gmail.com</td>
			</tr>
		</tbody></table>
</section>
<div class="section section-invoice-details">
	<div class="section-head">
		<h2 class="section-title section-title-alt">Invoice summary</h2><!-- /.section-title -->
	</div><!-- /.section-head -->

	<div class="section-body">
		<div class="table table-default table-default-primary">
			<table>
				<thead>
					<tr>
						<th>Description</th>
						<th>Amount</th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<td>Premium plan</td>
						<td>$ 30.00</td>
					</tr>
					<tr>
						<td>Services</td>
						<td>$ 6.24</td>
					</tr>
					<tr class="last">
						<td>Extras</td>
						<td>$ 0.00</td>
					</tr>
					<tr class="total">
						<td>TOTAL</td>
						<td><strong>$ 36.24</strong></td>
					</tr>
					<tr class="total">
						<td>VAT (17%)</td>
						<td>$ 6.16</td>
					</tr>
				</tbody>

				<tfoot>
					<tr class="grand-total">
						<td>GRAND TOTAL</td>
						<td>$ 42.00</td>
					</tr>
				</tfoot>
			</table>
		</div><!-- /.table table-default table-default-primary -->
	</div><!-- /.section-body -->
</div>